export enum Cuisine {
  American = 'AMERICAN',
  Austrian = 'AUSTRIAN',
  Chinese = 'CHINESE',
  CzechSlovak = 'CZECHSLOVAK',
  English = 'ENGLISH',
  Filipino = 'FILIPINO',
  French = 'FRENCH',
  Greek = 'GREEK',
  Indian = 'INDIAN',
  Italian = 'ITALIAN',
  Japanese = 'JAPANESE',
  Lebanese = 'LEBANESE',
  Mexican = 'MEXICAN',
  Spanish = 'SPANISH',
  Thai = 'THAI',
  Turkey = 'TURKEY',
}
