/**
 * Bulk recipe import — batch 2.
 * Usage:  npx ts-node src/import-recipes-2.ts
 */

import crypto from 'crypto';
import { getDB, seedFoods } from './db';

const uuid = () => crypto.randomUUID();

interface RecipeInput {
  name: string;
  description: string;
  cuisine: string;
  type: string;
  difficulty: string;
  time_value: number | null;
  time_unit: string;
  servings: number;
  wip: boolean;
  notes: string;
  tags: string[];
  ingredients: { name: string; qty: number | null; unit: string | null }[];
  steps: string[];
}

async function main() {
  const db = await getDB();
  await seedFoods();

  // Use first user
  const user = await db.get('SELECT id FROM users LIMIT 1');
  if (!user) {
    console.error('No user found! Run the first import script first.');
    process.exit(1);
  }
  const userId = user.id;
  console.log(`Using user: ${userId}`);

  // ── New foods ─────────────────────────────────────────
  const newFoods = [
    {
      id: 'f200',
      name: 'Semolina flour',
      name_it: 'Farina di semola',
      unit: 'GRAM',
      kcal: 360,
      protein: 12.7,
      fat: 1.1,
      carbs: 72.8,
      fiber: 3.9,
    },
    {
      id: 'f201',
      name: 'Poppy seeds',
      name_it: 'Semi di papavero',
      unit: 'GRAM',
      kcal: 525,
      protein: 17.9,
      fat: 41.6,
      carbs: 28.1,
      fiber: 19.5,
    },
    {
      id: 'f202',
      name: 'Potato starch',
      name_it: 'Fecola di patate',
      unit: 'GRAM',
      kcal: 333,
      protein: 0.1,
      fat: 0.0,
      carbs: 83.1,
      fiber: 0.0,
    },
    {
      id: 'f203',
      name: 'Dextrose',
      name_it: 'Destrosio',
      unit: 'GRAM',
      kcal: 360,
      protein: 0.0,
      fat: 0.0,
      carbs: 90.0,
      fiber: 0.0,
    },
    {
      id: 'f204',
      name: 'Powdered milk',
      name_it: 'Latte in polvere',
      unit: 'GRAM',
      kcal: 496,
      protein: 26.3,
      fat: 26.7,
      carbs: 38.4,
      fiber: 0.0,
    },
    {
      id: 'f205',
      name: 'Carob seed flour',
      name_it: 'Farina di semi di carrube',
      unit: 'GRAM',
      kcal: 222,
      protein: 4.6,
      fat: 0.7,
      carbs: 88.9,
      fiber: 39.8,
    },
    {
      id: 'f206',
      name: 'Saffron',
      name_it: 'Zafferano',
      unit: 'GRAM',
      kcal: 310,
      protein: 11.4,
      fat: 5.9,
      carbs: 65.4,
      fiber: 3.9,
    },
    {
      id: 'f207',
      name: 'Orange zest',
      name_it: 'Scorza di arancia',
      unit: 'PIECE',
      kcal: 97,
      protein: 1.5,
      fat: 0.2,
      carbs: 25.0,
      fiber: 10.6,
    },
    {
      id: 'f208',
      name: 'Walnuts',
      name_it: 'Noci',
      unit: 'GRAM',
      kcal: 654,
      protein: 15.2,
      fat: 65.2,
      carbs: 13.7,
      fiber: 6.7,
    },
    {
      id: 'f209',
      name: 'Philadelphia cream cheese',
      name_it: 'Philadelphia',
      unit: 'GRAM',
      kcal: 250,
      protein: 5.5,
      fat: 23.5,
      carbs: 4.0,
      fiber: 0.0,
    },
    {
      id: 'f210',
      name: 'Mustard',
      name_it: 'Senape',
      unit: 'GRAM',
      kcal: 66,
      protein: 4.4,
      fat: 3.3,
      carbs: 5.3,
      fiber: 3.3,
    },
    {
      id: 'f211',
      name: 'Alcohol vinegar',
      name_it: 'Aceto di alcool',
      unit: 'MILLILITER',
      kcal: 20,
      protein: 0.0,
      fat: 0.0,
      carbs: 0.6,
      fiber: 0.0,
    },
    {
      id: 'f212',
      name: 'Chickpea cooking water',
      name_it: 'Acqua di cottura dei ceci',
      unit: 'MILLILITER',
      kcal: 5,
      protein: 0.3,
      fat: 0.0,
      carbs: 0.8,
      fiber: 0.0,
    },
    {
      id: 'f213',
      name: 'Sunflower seed oil',
      name_it: 'Olio di semi di girasole',
      unit: 'MILLILITER',
      kcal: 884,
      protein: 0.0,
      fat: 100.0,
      carbs: 0.0,
      fiber: 0.0,
    },
    {
      id: 'f214',
      name: 'Pumpkin',
      name_it: 'Zucca',
      unit: 'GRAM',
      kcal: 26,
      protein: 1.0,
      fat: 0.1,
      carbs: 6.5,
      fiber: 0.5,
    },
    {
      id: 'f215',
      name: 'Rosemary',
      name_it: 'Rosmarino',
      unit: 'GRAM',
      kcal: 131,
      protein: 3.3,
      fat: 5.9,
      carbs: 20.7,
      fiber: 14.1,
    },
    {
      id: 'f216',
      name: 'Broth cube',
      name_it: 'Dado',
      unit: 'PIECE',
      kcal: 235,
      protein: 7.5,
      fat: 14.6,
      carbs: 18.2,
      fiber: 0.0,
    },
    {
      id: 'f217',
      name: 'Digestive biscuits',
      name_it: 'Biscotti digestive',
      unit: 'GRAM',
      kcal: 480,
      protein: 6.3,
      fat: 21.3,
      carbs: 66.7,
      fiber: 2.5,
    },
    {
      id: 'f218',
      name: 'Greek yogurt',
      name_it: 'Yogurt greco',
      unit: 'GRAM',
      kcal: 97,
      protein: 9.0,
      fat: 5.0,
      carbs: 3.6,
      fiber: 0.0,
    },
    {
      id: 'f219',
      name: 'Lemon zest',
      name_it: 'Scorza di limone',
      unit: 'PIECE',
      kcal: 47,
      protein: 1.5,
      fat: 0.3,
      carbs: 16.0,
      fiber: 10.6,
    },
    {
      id: 'f220',
      name: 'Raspberries',
      name_it: 'Lamponi',
      unit: 'GRAM',
      kcal: 52,
      protein: 1.2,
      fat: 0.7,
      carbs: 11.9,
      fiber: 6.5,
    },
    {
      id: 'f221',
      name: 'Almond flour',
      name_it: 'Farina di mandorle',
      unit: 'GRAM',
      kcal: 579,
      protein: 21.2,
      fat: 49.9,
      carbs: 21.6,
      fiber: 12.5,
    },
    {
      id: 'f222',
      name: 'Almond milk',
      name_it: 'Latte di mandorle',
      unit: 'MILLILITER',
      kcal: 17,
      protein: 0.6,
      fat: 1.1,
      carbs: 0.8,
      fiber: 0.2,
    },
    {
      id: 'f223',
      name: 'Almond paste',
      name_it: 'Pasta di mandorle',
      unit: 'GRAM',
      kcal: 458,
      protein: 9.0,
      fat: 27.7,
      carbs: 47.3,
      fiber: 4.0,
    },
    {
      id: 'f224',
      name: 'Coffee',
      name_it: 'Caffè',
      unit: 'GRAM',
      kcal: 2,
      protein: 0.1,
      fat: 0.0,
      carbs: 0.0,
      fiber: 0.0,
    },
    {
      id: 'f225',
      name: 'Sesame seeds',
      name_it: 'Semi di sesamo',
      unit: 'GRAM',
      kcal: 573,
      protein: 17.7,
      fat: 49.7,
      carbs: 23.4,
      fiber: 11.8,
    },
    {
      id: 'f226',
      name: 'Diastatic malt',
      name_it: 'Malto diastasico',
      unit: 'GRAM',
      kcal: 361,
      protein: 10.3,
      fat: 1.8,
      carbs: 78.3,
      fiber: 0.0,
    },
    {
      id: 'f227',
      name: 'Fresh yeast',
      name_it: 'Lievito di birra fresco',
      unit: 'GRAM',
      kcal: 105,
      protein: 8.4,
      fat: 1.9,
      carbs: 18.1,
      fiber: 7.6,
    },
    {
      id: 'f228',
      name: 'Rice',
      name_it: 'Riso',
      unit: 'GRAM',
      kcal: 130,
      protein: 2.7,
      fat: 0.3,
      carbs: 28.2,
      fiber: 0.4,
    },
    {
      id: 'f229',
      name: 'Cooked ham',
      name_it: 'Prosciutto cotto',
      unit: 'GRAM',
      kcal: 132,
      protein: 19.5,
      fat: 5.5,
      carbs: 1.5,
      fiber: 0.0,
    },
    {
      id: 'f230',
      name: 'Dark chocolate 70%',
      name_it: 'Cioccolato fondente 70%',
      unit: 'GRAM',
      kcal: 546,
      protein: 5.0,
      fat: 31.0,
      carbs: 60.0,
      fiber: 7.0,
    },
    {
      id: 'f231',
      name: 'Milk chocolate',
      name_it: 'Cioccolato al latte',
      unit: 'GRAM',
      kcal: 535,
      protein: 7.3,
      fat: 29.7,
      carbs: 59.4,
      fiber: 3.4,
    },
    {
      id: 'f232',
      name: 'Ginger',
      name_it: 'Zenzero',
      unit: 'GRAM',
      kcal: 80,
      protein: 1.8,
      fat: 0.8,
      carbs: 17.8,
      fiber: 2.0,
    },
    {
      id: 'f233',
      name: 'Curry powder',
      name_it: 'Curry',
      unit: 'GRAM',
      kcal: 325,
      protein: 14.3,
      fat: 14.0,
      carbs: 55.8,
      fiber: 33.2,
    },
    {
      id: 'f234',
      name: 'Chicken thighs',
      name_it: 'Sovracosce di pollo',
      unit: 'GRAM',
      kcal: 177,
      protein: 20.1,
      fat: 10.2,
      carbs: 0.0,
      fiber: 0.0,
    },
    {
      id: 'f235',
      name: 'Chocolate chips',
      name_it: 'Gocce di cioccolato',
      unit: 'GRAM',
      kcal: 479,
      protein: 5.0,
      fat: 25.0,
      carbs: 58.0,
      fiber: 3.0,
    },
    {
      id: 'f236',
      name: 'Red food coloring',
      name_it: 'Colorante rosso in gel',
      unit: 'GRAM',
      kcal: 0,
      protein: 0.0,
      fat: 0.0,
      carbs: 0.0,
      fiber: 0.0,
    },
    {
      id: 'f237',
      name: 'Apple cider vinegar',
      name_it: 'Aceto di mele',
      unit: 'MILLILITER',
      kcal: 21,
      protein: 0.0,
      fat: 0.0,
      carbs: 0.9,
      fiber: 0.0,
    },
    {
      id: 'f238',
      name: 'Lemon juice',
      name_it: 'Succo di limone',
      unit: 'MILLILITER',
      kcal: 22,
      protein: 0.4,
      fat: 0.2,
      carbs: 6.9,
      fiber: 0.3,
    },
    {
      id: 'f239',
      name: 'Chickpea flour',
      name_it: 'Farina di ceci',
      unit: 'GRAM',
      kcal: 387,
      protein: 22.4,
      fat: 6.7,
      carbs: 57.8,
      fiber: 10.8,
    },
    {
      id: 'f240',
      name: 'Tomato concentrate',
      name_it: 'Concentrato di pomodoro',
      unit: 'GRAM',
      kcal: 82,
      protein: 4.3,
      fat: 0.5,
      carbs: 18.9,
      fiber: 4.1,
    },
    {
      id: 'f241',
      name: 'Aquafaba',
      name_it: 'Acqua faba',
      unit: 'MILLILITER',
      kcal: 5,
      protein: 0.3,
      fat: 0.0,
      carbs: 0.8,
      fiber: 0.0,
    },
    {
      id: 'f242',
      name: 'Lemon juice',
      name_it: 'Succo di limone',
      unit: 'MILLILITER',
      kcal: 22,
      protein: 0.4,
      fat: 0.2,
      carbs: 6.9,
      fiber: 0.3,
    },
  ];

  const foodStmt = await db.prepare(
    `INSERT INTO foods (id, name, name_it, default_unit, kcal, protein, fat, carbs, fiber)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(id) DO UPDATE SET name_it=excluded.name_it, kcal=excluded.kcal, protein=excluded.protein, fat=excluded.fat, carbs=excluded.carbs, fiber=excluded.fiber`,
  );
  for (const f of newFoods) {
    await foodStmt.run(f.id, f.name, f.name_it, f.unit, f.kcal, f.protein, f.fat, f.carbs, f.fiber);
  }
  await foodStmt.finalize();
  console.log(`Seeded ${newFoods.length} new foods.`);

  // Build lookup
  const allFoods = await db.all('SELECT id, name, name_it, default_unit FROM foods');
  const foodMap = new Map<string, { id: string; unit: string }>();
  for (const f of allFoods) {
    if (f.name_it) foodMap.set(f.name_it.toLowerCase(), { id: f.id, unit: f.default_unit });
    if (f.name) foodMap.set(f.name.toLowerCase(), { id: f.id, unit: f.default_unit });
  }
  function findFood(name: string): { id: string; unit: string } | undefined {
    const n = name.toLowerCase().trim();
    if (foodMap.has(n)) return foodMap.get(n);
    for (const [key, val] of foodMap) {
      if (n.includes(key) || key.includes(n)) return val;
    }
    return undefined;
  }

  // ── Recipes ────────────────────────────────────────────────────
  const recipes: RecipeInput[] = [
    // ─── Formaggi ───
    {
      name: 'Primo sale',
      description: 'Formaggio primo sale fatto in casa.',
      cuisine: 'ITALIAN',
      type: 'OTHER',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes:
        'https://blog.giallozafferano.it/allacciateilgrembiule/formaggio-fatto-in-casa/\nhttps://blog.giallozafferano.it/ricettechepassione/formaggio-fatto-in-casa/\nhttps://m.youtube.com/watch?v=7DwWioTXYok',
      tags: ['formaggio'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Ricotta fatta in casa',
      description: 'Ricotta fresca fatta in casa.',
      cuisine: 'ITALIAN',
      type: 'OTHER',
      difficulty: 'EASY',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes:
        'https://blog.giallozafferano.it/allacciateilgrembiule/come-fare-la-ricotta/\nVariante con latte di capra e aceto di mele\nhttps://blog.giallozafferano.it/ricettechepassione/ricotta-fatta-in-casa/',
      tags: ['formaggio'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Mozzarella fatta in casa',
      description: 'Mozzarella homemade.',
      cuisine: 'ITALIAN',
      type: 'OTHER',
      difficulty: 'HARD',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes: 'https://www.instagram.com/reel/Cf9Y26CFMHs/?igshid=YmMyMTA2M2Y=',
      tags: ['formaggio'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Caprino fatto in casa',
      description: 'Formaggio caprino fatto in casa.',
      cuisine: 'ITALIAN',
      type: 'OTHER',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes: 'https://blog.giallozafferano.it/formaggio-caprino-fatto-in-casa/',
      tags: ['formaggio'],
      ingredients: [],
      steps: [],
    },
    // ─── Pasta fresca ───
    {
      name: 'Pasta fresca',
      description: "Pasta fresca all'uovo.",
      cuisine: 'ITALIAN',
      type: 'FIRSTCOURSE',
      difficulty: 'MEDIUM',
      time_value: 30,
      time_unit: 'MINUTE',
      servings: 2,
      wip: false,
      notes: 'Provare: 500g farina, 350g tuorli.',
      tags: ['pasta', 'base'],
      ingredients: [
        { name: 'Uova', qty: 2, unit: 'PIECE' },
        { name: 'Farina', qty: 150, unit: 'GRAM' },
        { name: 'Farina di semola', qty: 50, unit: 'GRAM' },
      ],
      steps: [],
    },
    {
      name: 'Pasta fresca senza uova',
      description: 'Pasta fresca vegana con semola.',
      cuisine: 'ITALIAN',
      type: 'FIRSTCOURSE',
      difficulty: 'EASY',
      time_value: 20,
      time_unit: 'MINUTE',
      servings: 2,
      wip: false,
      notes: '',
      tags: ['pasta', 'base', 'vegano'],
      ingredients: [
        { name: 'Farina di semola', qty: 200, unit: 'GRAM' },
        { name: 'Sale', qty: 3, unit: 'GRAM' },
      ],
      steps: [],
    },
    // ─── Bagel ───
    {
      name: 'Bagel',
      description: 'Bagel fatti in casa con semi di papavero.',
      cuisine: 'AMERICAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: 120,
      time_unit: 'MINUTE',
      servings: 5,
      wip: false,
      notes: '',
      tags: ['pane', 'lievitati'],
      ingredients: [
        { name: 'Farina 0', qty: 300, unit: 'GRAM' },
        { name: 'Lievito di birra secco', qty: 3.5, unit: 'GRAM' },
        { name: 'Sale', qty: 18, unit: 'GRAM' },
        { name: 'Zucchero di canna', qty: 28, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: 8, unit: 'MILLILITER' },
        { name: 'Fecola di patate', qty: 12, unit: 'GRAM' },
        { name: 'Semi di papavero', qty: null, unit: null },
      ],
      steps: [
        'Mescolare farina, lievito e sale. A parte amalgamare 150g acqua, zucchero e olio. Unire e impastare 15 minuti.',
        'Dividere in 5 palline, formare cilindri da 20cm e unire agli estremi formando ciambelle.',
        'Coprire con pellicola e far riposare 1 ora.',
        "Diluire la fecola in 150ml acqua, versare in pentola con 2 litri d'acqua. Portare a bollore.",
        'Immergere 2 bagel per volta, 1 min per lato. Scolare bene.',
        'Cospargere con semi di papavero. Forno 210°C per 20 minuti.',
      ],
    },
    // ─── Gelato ───
    {
      name: 'Gelato pistacchio/nocciola',
      description: 'Gelato fatto in casa con gelatiera.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: 60,
      time_unit: 'MINUTE',
      servings: 6,
      wip: false,
      notes:
        'Versione per latte 500ml: 522g latte, 144g zucchero, 12g destrosio, 180g panna, 36g latte in polvere, 5g carrube, 54g pasta.\nZatterini: 200g farina, 80g burro, 70g zucchero, 5g cacao, 1 uovo.',
      tags: ['dolce', 'gelato', 'pistacchio'],
      ingredients: [
        { name: 'Latte', qty: 435, unit: 'MILLILITER' },
        { name: 'Zucchero', qty: 120, unit: 'GRAM' },
        { name: 'Destrosio', qty: 10, unit: 'GRAM' },
        { name: 'Panna per dolci', qty: 150, unit: 'MILLILITER' },
        { name: 'Latte in polvere', qty: 30, unit: 'GRAM' },
        { name: 'Farina di semi di carrube', qty: 4, unit: 'GRAM' },
        { name: 'Pasta di pistacchi', qty: 45, unit: 'GRAM' },
      ],
      steps: [
        'Mescolare gli ingredienti in polvere.',
        'Scaldare latte e panna fino a lieve bollore. Versare sulle polveri e mescolare con frusta.',
        'Rimettere sul fuoco e portare a 85° per un paio di minuti.',
        'Togliere dal fuoco, far intiepidire, unire la pasta, emulsionare. Maturare in frigo (meglio tutta la notte).',
        'Trasferire in gelatiera a mantecare.',
      ],
    },
    {
      name: 'Gelato - Cialda cono',
      description: '',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 6,
      wip: true,
      notes: 'https://www.ilclubdellericette.it/ricetta/coni-cialde-gelato-fatti-casa',
      tags: ['dolce', 'gelato'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Gelato stracciatella',
      description: '',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 6,
      wip: true,
      notes: 'https://ricette.giallozafferano.it/Gelato-alla-stracciatella.html',
      tags: ['dolce', 'gelato'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Gelato fiordilatte',
      description: '',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 6,
      wip: true,
      notes: 'https://www.ilcuoreinpentola.it/ricette/dolci/gelati/gelato-fiordilatte/',
      tags: ['dolce', 'gelato'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Gelato biscotto',
      description: '',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 6,
      wip: true,
      notes: 'https://ricetta.it/gelato-biscotto',
      tags: ['dolce', 'gelato'],
      ingredients: [],
      steps: [],
    },
    // ─── Brioche messinesi ───
    {
      name: 'Brioche messinesi',
      description: 'Briosce col tuppo siciliane.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'HARD',
      time_value: 300,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes: 'https://www.soniaperonaci.it/brioscia-col-tuppo/',
      tags: ['dolce', 'lievitati', 'siciliano', 'colazione'],
      ingredients: [
        { name: 'Farina', qty: 600, unit: 'GRAM' },
        { name: 'Lievito di birra secco', qty: 7, unit: 'GRAM' },
        { name: 'Scorza di arancia', qty: null, unit: null },
        { name: 'Estratto di vaniglia', qty: null, unit: null },
        { name: 'Uova', qty: 2, unit: 'PIECE' },
        { name: 'Latte', qty: 250, unit: 'MILLILITER' },
        { name: 'Zafferano', qty: 0.5, unit: 'GRAM' },
        { name: 'Burro', qty: 100, unit: 'GRAM' },
        { name: 'Zucchero', qty: 100, unit: 'GRAM' },
        { name: 'Miele', qty: 15, unit: 'GRAM' },
        { name: 'Sale', qty: 12, unit: 'GRAM' },
      ],
      steps: [
        'In planetaria con gancio: farina setacciata, lievito e zucchero.',
        'In un bricchetto: latte, uova, tuorli, zafferano, miele, scorza di arancia. Sbattere e versare a filo.',
        'Impastare fino a incordatura. Aggiungere il burro 2-3 fiocchetti alla volta (almeno 15 min), alternando con il sale.',
        "Pirlare l'impasto, lievitare in ciotola unta 3 ore (forno spento con luce accesa). Deve triplicare.",
        'Dividere in 8 parti da ~150g. Attendere 30 min.',
        'Separare un pezzo piccolo per il tuppo. Formare la brioscia.',
        'Lievitare su teglia con carta forno 1 ora in forno spento.',
        'Spennellare con uovo sbattuto. Forno statico 170° per 20-25 min.',
      ],
    },
    // ─── Focaccia patate (PIENA — sovrascrive WIP) ───
    {
      name: 'Focaccia patate',
      description: 'Focaccia morbida con patate.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: 180,
      time_unit: 'MINUTE',
      servings: 6,
      wip: false,
      notes:
        'Provare variante zucca: 400g farina media forza, 185g acqua, 300g zucca delica, 30g acqua per zucca, 9g lievito fresco, 1/2 cucchiaino curcuma, 12g sale, 20g olio. Salamoia: 30g olio, 30g acqua, sale.',
      tags: ['focaccia', 'patate', 'lievitati'],
      ingredients: [
        { name: 'Farina manitoba', qty: 350, unit: 'GRAM' },
        { name: 'Farina', qty: 250, unit: 'GRAM' },
        { name: 'Patata', qty: 500, unit: 'GRAM' },
        { name: 'Sale', qty: 16, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: 100, unit: 'MILLILITER' },
        { name: 'Lievito di birra secco', qty: 7, unit: 'GRAM' },
        { name: 'Malto in polvere', qty: 5, unit: 'GRAM' },
      ],
      steps: [],
    },
    // ─── Bignè ───
    {
      name: 'Bignè',
      description: '',
      cuisine: 'FRENCH',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 12,
      wip: true,
      notes: 'https://vm.tiktok.com/ZMFMVWKLb/',
      tags: ['dolce'],
      ingredients: [],
      steps: [],
    },
    // ─── Caramello Salato ───
    {
      name: 'Caramello Salato',
      description: 'Salsa al caramello salato.',
      cuisine: 'FRENCH',
      type: 'OTHER',
      difficulty: 'EASY',
      time_value: 15,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes: '',
      tags: ['dolce', 'salsa'],
      ingredients: [
        { name: 'Zucchero', qty: 100, unit: 'GRAM' },
        { name: 'Burro', qty: 40, unit: 'GRAM' },
        { name: 'Panna per dolci', qty: 60, unit: 'MILLILITER' },
        { name: 'Sale', qty: null, unit: null },
      ],
      steps: [],
    },
    // ─── Carrot Cake ───
    {
      name: 'Carrot Cake',
      description: 'Torta di carote con crema al formaggio.',
      cuisine: 'AMERICAN',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: 60,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes: 'https://www.tavolartegusto.it/ricetta/carrot-cake-ricetta-originale/',
      tags: ['dolce', 'carote', 'americano'],
      ingredients: [
        { name: 'Farina', qty: 300, unit: 'GRAM' },
        { name: 'Carota', qty: 300, unit: 'GRAM' },
        { name: 'Olio di semi di girasole', qty: 240, unit: 'MILLILITER' },
        { name: 'Zucchero di canna', qty: 230, unit: 'GRAM' },
        { name: 'Uova', qty: 4, unit: 'PIECE' },
        { name: 'Noci', qty: 100, unit: 'GRAM' },
        { name: 'Cannella', qty: 5, unit: 'GRAM' },
        { name: 'Estratto di vaniglia', qty: 5, unit: 'MILLILITER' },
        { name: 'Lievito per dolci', qty: 16, unit: 'GRAM' },
        { name: 'Bicarbonato', qty: 5, unit: 'GRAM' },
        { name: 'Philadelphia', qty: 500, unit: 'GRAM' },
        { name: 'Zucchero a velo', qty: 200, unit: 'GRAM' },
        { name: 'Estratto di vaniglia', qty: 10, unit: 'MILLILITER' },
      ],
      steps: [
        'Mescolare farina, cannella, lievito e bicarbonato.',
        'A parte lavorare uova, zucchero, olio e vaniglia. Unire carote grattugiate e noci.',
        'Unire i composti. Forno statico 180° per 40-50 min.',
        'Crema: montare Philadelphia, zucchero a velo e vaniglia.',
        'Farcire e decorare con noci.',
      ],
    },
    // ─── Maionese vegana ───
    {
      name: 'Maionese vegana',
      description: 'Maionese vegetale con aquafaba.',
      cuisine: 'ITALIAN',
      type: 'OTHER',
      difficulty: 'EASY',
      time_value: 10,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes: '',
      tags: ['salsa', 'vegano'],
      ingredients: [
        { name: 'Acqua di cottura dei ceci', qty: 100, unit: 'MILLILITER' },
        { name: 'Olio di semi di girasole', qty: 150, unit: 'MILLILITER' },
        { name: 'Senape', qty: 10, unit: 'GRAM' },
        { name: 'Aceto di alcool', qty: 5, unit: 'MILLILITER' },
        { name: 'Sale', qty: null, unit: null },
        { name: 'Farina di semi di carrube', qty: 5, unit: 'GRAM' },
      ],
      steps: [],
    },
    // ─── Polpette zucca ───
    {
      name: 'Polpette di zucca',
      description: '',
      cuisine: 'ITALIAN',
      type: 'SECONDCOURSE',
      difficulty: 'EASY',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes:
        'https://ricette.giallozafferano.it/Polpette-di-zucca.html\nhttps://www.ziaralu.it/recipe/crocchette-di-zucca-ricetta-facile/',
      tags: ['secondo', 'zucca', 'vegetariano'],
      ingredients: [],
      steps: [],
    },
    // ─── Tigelle ───
    {
      name: 'Tigelle',
      description: 'Crescentine emiliane cotte in tigelliera.',
      cuisine: 'ITALIAN',
      type: 'OTHER',
      difficulty: 'MEDIUM',
      time_value: 720,
      time_unit: 'MINUTE',
      servings: 50,
      wip: false,
      notes: '',
      tags: ['pane', 'emiliano'],
      ingredients: [
        { name: 'Farina 0', qty: 250, unit: 'GRAM' },
        { name: 'Farina', qty: 500, unit: 'GRAM' },
        { name: 'Latte', qty: 300, unit: 'MILLILITER' },
        { name: 'Strutto', qty: 60, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: 50, unit: 'MILLILITER' },
        { name: 'Lievito di birra secco', qty: 3, unit: 'GRAM' },
        { name: 'Sale', qty: 8, unit: 'GRAM' },
      ],
      steps: [
        'In planetaria: farine, latte, lievito, strutto. Gancio 1 min.',
        'Aggiungere olio e acqua (200g). Continuare col gancio. Aggiungere sale quando si stacca.',
        'Gancio per 6 min fino a impasto compatto. Lavorare a mano fino a liscio.',
        'Lievitare 2 ore coperto a temperatura ambiente. Poi frigo per almeno 8 ore.',
        'Stendere a 5mm. Coppapasta 8.5cm per fare i dischi. Riposare 20 minuti.',
        'Tigelliera calda a fuoco moderato. Cuocere 4-5 minuti per lato, controllando.',
        'Coprire con canovaccio per mantenerle morbide.',
      ],
    },
    // ─── Pasta frolla ───
    {
      name: 'Pasta frolla',
      description: 'Pasta frolla classica per crostate e biscotti.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 45,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes: '',
      tags: ['dolce', 'base'],
      ingredients: [
        { name: 'Farina', qty: 250, unit: 'GRAM' },
        { name: 'Uova', qty: 1, unit: 'PIECE' },
        { name: 'Burro', qty: 125, unit: 'GRAM' },
        { name: 'Zucchero', qty: 100, unit: 'GRAM' },
        { name: 'Miele', qty: 20, unit: 'GRAM' },
        { name: 'Bicarbonato', qty: 3, unit: 'GRAM' },
      ],
      steps: [
        'Impastatrice con gancio a foglia: sabbiatura con farina e burro.',
        'Aggiungere il resto e compattare.',
        'Pellicola e frigo per 30 min.',
        'Forno: 150-170°.',
      ],
    },
    // ─── Crema Pasticcera ───
    {
      name: 'Crema Pasticcera',
      description: '',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes: 'https://ricette.giallozafferano.it/Crema-pasticcera.html',
      tags: ['dolce', 'crema', 'base'],
      ingredients: [],
      steps: [],
    },
    // ─── Maritozzi ───
    {
      name: 'Maritozzi',
      description: '',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 8,
      wip: true,
      notes: 'https://www.fattoincasadabenedetta.it/ricetta/maritozzi/',
      tags: ['dolce', 'lievitati', 'romano'],
      ingredients: [],
      steps: [],
    },
    // ─── Canestrelli ───
    {
      name: 'Canestrelli',
      description: '',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 20,
      wip: true,
      notes: 'https://www.soniaperonaci.it/canestrelli/',
      tags: ['dolce', 'biscotti'],
      ingredients: [],
      steps: [],
    },
    // ─── Palline di patate ───
    {
      name: 'Palline di patate',
      description: '',
      cuisine: 'ITALIAN',
      type: 'APPETIZER',
      difficulty: 'EASY',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes: 'https://www.instagram.com/reel/CoAX2mrAEX5/?igshid=YmMyMTA2M2Y=',
      tags: ['antipasto', 'patate'],
      ingredients: [],
      steps: [],
    },
    // ─── Focaccine ───
    {
      name: 'Focaccine',
      description: 'Focaccine morbide fatte in casa.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'EASY',
      time_value: 120,
      time_unit: 'MINUTE',
      servings: 12,
      wip: false,
      notes: '',
      tags: ['focaccia', 'lievitati'],
      ingredients: [
        { name: 'Farina', qty: 200, unit: 'GRAM' },
        { name: 'Farina manitoba', qty: 200, unit: 'GRAM' },
        { name: 'Lievito di birra secco', qty: 4, unit: 'GRAM' },
        { name: 'Zucchero', qty: 20, unit: 'GRAM' },
        { name: 'Sale', qty: 10, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: 50, unit: 'MILLILITER' },
        { name: 'Latte', qty: 125, unit: 'MILLILITER' },
      ],
      steps: [
        'Impastare tutto fino a panetto liscio e omogeneo. Lievitare 1h.',
        'Stendere a mezzo cm, formare dischetti con coppapasta. Lievitare fino al raddoppio.',
        'Fare buchi con le dita. Spennellare con acqua e olio. Aggiungere sale, pepe, rosmarino a piacere.',
        '180°C per 20-25 minuti. Spennellare con acqua in uscita se troppo croccanti.',
      ],
    },
    // ─── Trdelnik ───
    {
      name: 'Trdelník',
      description: '',
      cuisine: 'CZECHSLOVAK',
      type: 'YEASTPRODUCTS',
      difficulty: 'HARD',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 6,
      wip: true,
      notes: 'https://www.lecosmopolite.it/trdlo-ricetta/amp/\nhttps://vm.tiktok.com/ZMY6KgLBx/',
      tags: ['dolce', 'lievitati'],
      ingredients: [],
      steps: [],
    },
    // ─── Vellutata di zucca ───
    {
      name: 'Vellutata di zucca',
      description: 'Crema di zucca calda.',
      cuisine: 'ITALIAN',
      type: 'FIRSTCOURSE',
      difficulty: 'EASY',
      time_value: 40,
      time_unit: 'MINUTE',
      servings: 2,
      wip: false,
      notes:
        'Senza brodo: aggiungere più sale.\nhttps://www.tavolartegusto.it/ricetta/crema-di-zucca/amp/',
      tags: ['primo', 'zucca', 'vegetariano'],
      ingredients: [
        { name: 'Zucca', qty: 400, unit: 'GRAM' },
        { name: 'Patata', qty: 100, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: 15, unit: 'MILLILITER' },
        { name: 'Cipolla', qty: null, unit: null },
        { name: 'Rosmarino', qty: null, unit: null },
        { name: 'Pepe nero', qty: null, unit: null },
        { name: 'Noce moscata', qty: null, unit: null },
      ],
      steps: [
        'Tagliare tutto a pezzetti e mettere in pentola con olio e spezie.',
        'Rosolare e aggiungere 300g di brodo caldo (acqua + 1/4 dado).',
        'Chiudere con coperchio per 30 minuti.',
        'Frullare tutto. Acqua se troppo asciutto, fuoco se troppo liquido. Sale q.b.',
      ],
    },
    // ─── Caviale di basilico ───
    {
      name: 'Caviale di basilico',
      description: '',
      cuisine: 'ITALIAN',
      type: 'APPETIZER',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes: 'https://vm.tiktok.com/ZMYDnPq7d/',
      tags: ['antipasto'],
      ingredients: [],
      steps: [],
    },
    // ─── Pane in cassetta ───
    {
      name: 'Pane in cassetta',
      description: 'Pan bauletto fatto in casa.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: 120,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes:
        'https://blog.cookaround.com/lamimosarosa/pan-bauletto/\nhttps://blog.giallozafferano.it/maniinfrolla/pane-morbido-in-cassetta-extra-soffice/\nhttps://vm.tiktok.com/ZMYurJa3C/',
      tags: ['pane', 'lievitati'],
      ingredients: [
        { name: 'Farina 0', qty: 150, unit: 'GRAM' },
        { name: 'Lievito di birra secco', qty: 1, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: 8, unit: 'MILLILITER' },
        { name: 'Malto in polvere', qty: 1.5, unit: 'GRAM' },
        { name: 'Sale', qty: 3, unit: 'GRAM' },
      ],
      steps: [],
    },
    // ─── Pizzette ───
    {
      name: 'Pizzette',
      description: 'Pizzette da rosticceria.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'EASY',
      time_value: 120,
      time_unit: 'MINUTE',
      servings: 6,
      wip: false,
      notes: 'Provare: eliminare latte, autolisi 30 min.',
      tags: ['pizza', 'lievitati'],
      ingredients: [
        { name: 'Farina manitoba', qty: 500, unit: 'GRAM' },
        { name: 'Latte', qty: 220, unit: 'MILLILITER' },
        { name: 'Lievito di birra fresco', qty: 12, unit: 'GRAM' },
        { name: 'Sale', qty: 15, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: 15, unit: 'MILLILITER' },
      ],
      steps: [],
    },
    // ─── Arancine ───
    {
      name: 'Arancine',
      description: 'Arancine siciliane al ragù e besciamella.',
      cuisine: 'ITALIAN',
      type: 'APPETIZER',
      difficulty: 'HARD',
      time_value: 120,
      time_unit: 'MINUTE',
      servings: 6,
      wip: false,
      notes:
        'Cose da provare: condimento il giorno prima, cucchiaio di grana nella besciamella, meno dado e più sale/pepe, burro per mantecare, colorante al posto dello zafferano.\nPer arancinette: uguale ma senza besciamella.\nhttps://www.tuorlorosso.it/arancinette-palermitane/\nhttps://www.instagram.com/reel/Cn9qy5Vo7ry/',
      tags: ['antipasto', 'siciliano', 'fritto'],
      ingredients: [
        { name: 'Riso', qty: 250, unit: 'GRAM' },
        { name: 'Zafferano', qty: 0.5, unit: 'GRAM' },
        { name: 'Sale', qty: 5, unit: 'GRAM' },
        { name: 'Dado', qty: 0.5, unit: 'PIECE' },
        { name: 'Burro', qty: 30, unit: 'GRAM' },
        { name: 'Besciamella', qty: 50, unit: 'MILLILITER' },
        { name: 'Grana padano', qty: 20, unit: 'GRAM' },
        { name: 'Prosciutto cotto', qty: 100, unit: 'GRAM' },
        { name: 'Mozzarella', qty: 100, unit: 'GRAM' },
      ],
      steps: [
        'Riso: unire riso (250g), acqua (650g), zafferano, sale, dado a freddo. Cuocere a fiamma bassa con coperchio. Riporre in frigo una notte.',
        'Condire con besciamella, grana, prosciutto e mozzarella.',
        'Formare le arancine con legame di acqua e farina.',
        'Friggere.',
      ],
    },
    // ─── Tiramisù ───
    {
      name: 'Tiramisù',
      description: '',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 6,
      wip: true,
      notes:
        'https://ricette.giallozafferano.it/come-pastorizzare-le-uova.html\nhttps://ricette.giallozafferano.it/Tiramisu.html',
      tags: ['dolce', 'classico'],
      ingredients: [],
      steps: [],
    },
    // ─── Focaccia noci ───
    {
      name: 'Focaccia noci',
      description: 'Focaccia alle noci, olive e semi di papavero.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 6,
      wip: true,
      notes: '',
      tags: ['focaccia', 'lievitati', 'noci'],
      ingredients: [],
      steps: [],
    },
    // ─── Pane bianco ───
    {
      name: 'Pane bianco',
      description: 'Pane bianco soffice tipo semprefreschi.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'EASY',
      time_value: 240,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes: '',
      tags: ['pane', 'lievitati'],
      ingredients: [
        { name: 'Farina', qty: 500, unit: 'GRAM' },
        { name: 'Lievito di birra fresco', qty: 10, unit: 'GRAM' },
        { name: 'Zucchero', qty: 10, unit: 'GRAM' },
        { name: 'Sale', qty: 10, unit: 'GRAM' },
      ],
      steps: [
        'Sciogliere il lievito con acqua (300g) e zucchero.',
        'Impastare il tutto lasciando una parte di acqua e il sale alla fine.',
        '2-3 ore di lievitazione. 1-2 ore in teglia.',
        '5-10 min a 250° + 5-10 min a 200°.',
      ],
    },
    // ─── Pane di paese ───
    {
      name: 'Pane di paese',
      description: 'Pane siciliano con sesamo.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: 180,
      time_unit: 'MINUTE',
      servings: 6,
      wip: false,
      notes:
        'https://blog.giallozafferano.it/letortedigessica/pane-siciliano-con-sesamo-lievito-madre-birra/amp/',
      tags: ['pane', 'lievitati', 'siciliano'],
      ingredients: [
        { name: 'Farina di semola', qty: 350, unit: 'GRAM' },
        { name: 'Farina', qty: 150, unit: 'GRAM' },
        { name: 'Lievito di birra fresco', qty: 20, unit: 'GRAM' },
        { name: 'Sale', qty: 10, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: 30, unit: 'MILLILITER' },
        { name: 'Malto diastasico', qty: 5, unit: 'GRAM' },
        { name: 'Semi di sesamo', qty: null, unit: null },
      ],
      steps: ['210° 15 min, 190° 15 min, grata 10 min.'],
    },
    // ─── Gnocchi di zucca ───
    {
      name: 'Gnocchi di zucca',
      description: '',
      cuisine: 'ITALIAN',
      type: 'FIRSTCOURSE',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes:
        'Provare fecola per addensare.\nhttps://www.fattoincasadabenedetta.it/ricetta/gnocchi-di-zucca-fatti-in-casa-da-benedetta/',
      tags: ['primo', 'zucca'],
      ingredients: [],
      steps: [],
    },
    // ─── Pasta Brisè ───
    {
      name: 'Pasta Brisè',
      description: 'Pasta brisée per torte salate.',
      cuisine: 'FRENCH',
      type: 'OTHER',
      difficulty: 'EASY',
      time_value: 70,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes: 'Provare: 200g farina, 80g burro freddo, 60g acqua freddissima, 5g sale.',
      tags: ['base', 'salato'],
      ingredients: [
        { name: 'Farina', qty: 200, unit: 'GRAM' },
        { name: 'Burro', qty: 60, unit: 'GRAM' },
        { name: 'Sale', qty: 5, unit: 'GRAM' },
      ],
      steps: [
        'Sabbiatura con farina e burro.',
        'Aggiungere acqua ghiacciata (70g) e sale e creare un panetto senza lavorare troppo.',
        'Riposo in frigo per 1 ora circa.',
      ],
    },
    // ─── Liquore ───
    {
      name: "Liquore al fico d'India",
      description: "Liquore fatto in casa con fichi d'India.",
      cuisine: 'ITALIAN',
      type: 'BEVERAGE',
      difficulty: 'EASY',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 10,
      wip: false,
      notes:
        "In mezzo litro di alcool mettere 4-5 fichi d'India viola. Macerare un mese. Colare. Fare sciroppo con 750ml acqua e 375g zucchero. Raffreddare e unire. Riposare un mese al buio. Conservare in freezer.\nhttps://ricette.giallozafferano.it/Limoncello.html",
      tags: ['bevanda', 'liquore'],
      ingredients: [],
      steps: [],
    },
    // ─── Brioscine panificio ───
    {
      name: 'Brioscine panificio',
      description: 'Brioches da panificio.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: 180,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes:
        '10min a 220° + 5min a 180°. Provare 8-9min a 250° e poi scendere.\nhttps://cookandlove.it/2016/06/17/cornetto-brioscato-morbidezza-a-prova-giorno-dopo/',
      tags: ['dolce', 'lievitati', 'colazione'],
      ingredients: [
        { name: 'Farina', qty: 250, unit: 'GRAM' },
        { name: 'Strutto', qty: 25, unit: 'GRAM' },
        { name: 'Zucchero', qty: 25, unit: 'GRAM' },
        { name: 'Sale', qty: 5, unit: 'GRAM' },
        { name: 'Lievito di birra secco', qty: 2, unit: 'GRAM' },
        { name: 'Gocce di cioccolato', qty: 60, unit: 'GRAM' },
      ],
      steps: [
        'Sciogliere il lievito con acqua (125g) e zuccheri.',
        'Aggiungere farina, poi strutto pezzetto per pezzetto fino ad assorbimento.',
        'Lievitare fino al raddoppio. Separare in panetti da 60g. Lievitare nuovamente.',
        'Spennellare con uovo. Forno preriscaldato 180° per 20 min circa.',
      ],
    },
    // ─── Taralli pugliesi ───
    {
      name: 'Taralli pugliesi',
      description: '',
      cuisine: 'ITALIAN',
      type: 'OTHER',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 20,
      wip: true,
      notes:
        'https://www.tipikoshop.it/taralli-pugliesi-super-friabili-e-golosi-la-ricetta-tradizionale-pugliese/',
      tags: ['snack', 'pugliese'],
      ingredients: [],
      steps: [],
    },
    // ─── Gnocchi ───
    {
      name: 'Gnocchi',
      description: 'Gnocchi di patate fatti in casa.',
      cuisine: 'ITALIAN',
      type: 'FIRSTCOURSE',
      difficulty: 'EASY',
      time_value: 40,
      time_unit: 'MINUTE',
      servings: 2,
      wip: false,
      notes: 'Provare: 300g patate, 85g farina 0, 15g fecola di patate, pizzico di sale.',
      tags: ['primo', 'patate'],
      ingredients: [
        { name: 'Patata', qty: 300, unit: 'GRAM' },
        { name: 'Farina 0', qty: 100, unit: 'GRAM' },
        { name: 'Sale', qty: null, unit: null },
      ],
      steps: [
        'Bollire le patate con la buccia. Asciugare e far intiepidire.',
        'Mescolare fino a che non si attacca. Aggiungere farina poco alla volta se serve.',
        'Fare i serpentini, aiutandosi con farina di semola sul tavolo.',
      ],
    },
    // ─── Cornetto ───
    {
      name: 'Cornetto',
      description: '',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'HARD',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 8,
      wip: true,
      notes:
        'Cornetto italiano: https://www.ilclubdellericette.it/ricetta/cornetti-fatti-in-casa/\nCroissant (senza uova): https://natashasbaking.com/croissant-yeast-method/\nhttps://vm.tiktok.com/ZMYur2goG/\nhttps://www.cookergirl.it/croissants-non-e-ancora-finita/',
      tags: ['dolce', 'lievitati', 'colazione'],
      ingredients: [],
      steps: [],
    },
    // ─── Boxty ───
    {
      name: 'Boxty',
      description: '',
      cuisine: 'ENGLISH',
      type: 'SIDE',
      difficulty: 'EASY',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes: 'https://vm.tiktok.com/ZGJnq5WHw/',
      tags: ['contorno', 'patate', 'irlandese'],
      ingredients: [],
      steps: [],
    },
    // ─── Cocktail blu/Viola ───
    {
      name: 'Cocktail blu/Viola',
      description: 'Cocktail con fiori di pisello e limone.',
      cuisine: 'ITALIAN',
      type: 'BEVERAGE',
      difficulty: 'EASY',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 2,
      wip: true,
      notes: 'Fiori di pisello + limone\nhttps://vm.tiktok.com/ZGJnqAgCg/',
      tags: ['bevanda', 'cocktail'],
      ingredients: [],
      steps: [],
    },
    // ─── Pizza a taglio ───
    {
      name: 'Pizza a taglio',
      description: '',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes:
        'https://www.lacucinaditricchitrocchi.it/pizza-siciliana-in-teglia/\nhttps://www.ricettedalmondo.it/sfincione-palermitano.html',
      tags: ['pizza', 'siciliano'],
      ingredients: [],
      steps: [],
    },
    // ─── Pizza Spontini ───
    {
      name: 'Pizza Spontini',
      description: 'Pizza alta tipo Spontini Milano.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes:
        'https://laconfraternitadellapizza.forumfree.it/m/?t=75173340\nhttps://www.pizzaefocaccia.it/impasto-no-knead/',
      tags: ['pizza', 'milanese'],
      ingredients: [
        { name: 'Farina manitoba', qty: 500, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: 25, unit: 'MILLILITER' },
        { name: 'Sale', qty: 12, unit: 'GRAM' },
        { name: 'Lievito di birra secco', qty: 1, unit: 'GRAM' },
      ],
      steps: [],
    },
    // ─── Pizza Contemporanea ───
    {
      name: 'Pizza Contemporanea',
      description: 'Pizza in padella con cottura grill.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 3,
      wip: false,
      notes:
        "Note:\n1. La proporzione di farine la sto ancora sperimentando. Per la lunga levitazione è importante usare farine forti. Mescolo pure Manitoba per assorbire meglio l'acqua.\n2. Idratazione consigliata con impastatrice o buona manualità.\n3. Più lievito per temperature basse, meno per alte.\n4. Acqua ambiente per temp basse, acqua fredda per alte.\n5. Sera prima faccio impasto, panetti a pranzo del giorno dopo.\n6. Le piastre del grill devono rimanere sempre accese (rosse).\n7. Attenzione a non far bruciare la carta forno.",
      tags: ['pizza'],
      ingredients: [
        { name: 'Farina', qty: 500, unit: 'GRAM' },
        { name: 'Lievito di birra secco', qty: 2, unit: 'GRAM' },
        { name: 'Sale', qty: 15, unit: 'GRAM' },
      ],
      steps: [
        'Mettere in frigo per 30 min tutti gli ingredienti.',
        'Mescolare aggiungendo acqua (360-375g) poco alla volta. Sale solo alla fine.',
        'Chiudere impasto in ciotola oleata e pellicola in frigo tutta la notte.',
        'Creare 3 panetti con semola. Riposare 5 ore in forno spento.',
        'Scaldare grande padella a fuoco alto per 5 min. Accendere grill forno a max.',
        'Stendere su carta forno, farcire.',
        'Cuocere il sotto in padella per 3 min.',
        'Cuocere il sopra in forno ultimo livello (~5cm dalle piastre) per almeno 3 min.',
      ],
    },
    // ─── Brioscione ───
    {
      name: 'Brioscione',
      description: 'Brioscia grande siciliana.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes: 'https://vm.tiktok.com/ZGe7qVYYe/',
      tags: ['lievitati', 'siciliano'],
      ingredients: [
        { name: 'Farina', qty: 250, unit: 'GRAM' },
        { name: 'Farina manitoba', qty: 250, unit: 'GRAM' },
        { name: 'Latte', qty: 330, unit: 'MILLILITER' },
        { name: 'Lievito di birra fresco', qty: 12, unit: 'GRAM' },
        { name: 'Zucchero', qty: 50, unit: 'GRAM' },
        { name: 'Strutto', qty: 60, unit: 'GRAM' },
        { name: 'Sale', qty: 10, unit: 'GRAM' },
        { name: 'Semi di sesamo', qty: null, unit: null },
      ],
      steps: [],
    },
    // ─── Crostata ───
    {
      name: 'Crostata',
      description: 'Crostata classica con marmellata.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 45,
      time_unit: 'MINUTE',
      servings: 6,
      wip: false,
      notes: 'Variante con crema pasticcera: https://www.instagram.com/reel/CnOZrE_BJyF/',
      tags: ['dolce', 'classico'],
      ingredients: [
        { name: 'Farina', qty: 250, unit: 'GRAM' },
        { name: 'Uova', qty: 1, unit: 'PIECE' },
        { name: 'Burro', qty: 80, unit: 'GRAM' },
        { name: 'Zucchero', qty: 66, unit: 'GRAM' },
        { name: 'Lievito per dolci', qty: 10, unit: 'GRAM' },
        { name: 'Scorza di limone', qty: null, unit: null },
        { name: 'Sale', qty: null, unit: null },
      ],
      steps: [],
    },
    // ─── Rosticceria ───
    {
      name: 'Rosticceria',
      description: 'Impasto base per rosticceria siciliana.',
      cuisine: 'ITALIAN',
      type: 'OTHER',
      difficulty: 'MEDIUM',
      time_value: 240,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes: 'Meno lievito.',
      tags: ['rosticceria', 'siciliano', 'lievitati'],
      ingredients: [
        { name: 'Farina', qty: 500, unit: 'GRAM' },
        { name: 'Zucchero', qty: 25, unit: 'GRAM' },
        { name: 'Sale', qty: 12, unit: 'GRAM' },
        { name: 'Lievito di birra fresco', qty: 20, unit: 'GRAM' },
        { name: 'Strutto', qty: 50, unit: 'GRAM' },
      ],
      steps: [
        'Sciogliere il lievito con acqua (300g) e zucchero. Impastare lasciando sale alla fine.',
        '2-3 ore lievitazione. 1 ora panetti separati.',
        'Condire a piacere, aspettare 30 min.',
        'Spennellare con uovo. Infornare 10-15 min a 220-250° ventilato.',
      ],
    },
    // ─── Pollo al curry ───
    {
      name: 'Pollo al curry',
      description: 'Pollo al curry con yogurt greco.',
      cuisine: 'INDIAN',
      type: 'SECONDCOURSE',
      difficulty: 'EASY',
      time_value: 40,
      time_unit: 'MINUTE',
      servings: 2,
      wip: false,
      notes: 'https://ricette.giallozafferano.it/Pollo-al-curry.html',
      tags: ['secondo', 'pollo', 'curry'],
      ingredients: [
        { name: 'Sovracosce di pollo', qty: 600, unit: 'GRAM' },
        { name: 'Yogurt greco', qty: 100, unit: 'GRAM' },
        { name: 'Curry', qty: 8, unit: 'GRAM' },
        { name: 'Aglio', qty: 0.5, unit: 'PIECE' },
        { name: 'Cipolla', qty: 40, unit: 'GRAM' },
        { name: 'Zenzero', qty: 10, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: null, unit: null },
      ],
      steps: [
        'Disossare pollo e tagliare a 3cm.',
        'Soffritto di aglio, cipolla, zenzero. Aggiungere curry.',
        'Aggiungere pollo, rosolare. Aggiungere acqua, coprire 20-30 min.',
        'Spegnere e aggiungere yogurt.',
      ],
    },
    // ─── Tortini carote e noci ───
    {
      name: 'Tortini carote e noci',
      description: 'Mini tortini con carote grattugiate e noci.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 30,
      time_unit: 'MINUTE',
      servings: 6,
      wip: false,
      notes: '',
      tags: ['dolce', 'carote'],
      ingredients: [
        { name: 'Uova', qty: 1, unit: 'PIECE' },
        { name: 'Carota', qty: 130, unit: 'GRAM' },
        { name: 'Noci', qty: 50, unit: 'GRAM' },
        { name: 'Zucchero di canna', qty: 80, unit: 'GRAM' },
        { name: 'Latte', qty: 50, unit: 'MILLILITER' },
        { name: 'Olio di semi di girasole', qty: 50, unit: 'MILLILITER' },
        { name: 'Farina', qty: 140, unit: 'GRAM' },
        { name: 'Lievito per dolci', qty: 8, unit: 'GRAM' },
        { name: 'Scorza di arancia', qty: null, unit: null },
      ],
      steps: [],
    },
    // ─── Torta Red Velvet ───
    {
      name: 'Torta Red Velvet',
      description: 'Red velvet cake con crema al formaggio.',
      cuisine: 'AMERICAN',
      type: 'DESSERT',
      difficulty: 'HARD',
      time_value: 90,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes:
        "Evitare lo shock termico: spegnere il forno, aspettare un po', aprire sportello, aspettare, togliere torta, aspettare mezz'ora, rimuovere dallo stampo.",
      tags: ['dolce', 'americano'],
      ingredients: [
        { name: 'Farina', qty: 250, unit: 'GRAM' },
        { name: 'Burro', qty: 120, unit: 'GRAM' },
        { name: 'Zucchero', qty: 240, unit: 'GRAM' },
        { name: 'Uova', qty: 3, unit: 'PIECE' },
        { name: 'Estratto di vaniglia', qty: 15, unit: 'MILLILITER' },
        { name: 'Cacao amaro', qty: 10, unit: 'GRAM' },
        { name: 'Colorante rosso in gel', qty: 5, unit: 'GRAM' },
        { name: 'Aceto di mele', qty: 5, unit: 'MILLILITER' },
        { name: 'Bicarbonato', qty: 5, unit: 'GRAM' },
        { name: 'Sale', qty: null, unit: null },
        { name: 'Philadelphia', qty: 375, unit: 'GRAM' },
        { name: 'Mascarpone', qty: 250, unit: 'GRAM' },
        { name: 'Panna per dolci', qty: 200, unit: 'MILLILITER' },
        { name: 'Zucchero a velo', qty: 150, unit: 'GRAM' },
        { name: 'Latte', qty: 125, unit: 'MILLILITER' },
        { name: 'Yogurt greco', qty: 125, unit: 'GRAM' },
        { name: 'Succo di limone', qty: 5, unit: 'MILLILITER' },
      ],
      steps: [
        'Latticello: latte, yogurt e succo di limone. Riposare 15-20 min.',
        'In planetaria: burro e zucchero fino a spumoso (~10 min). Aggiungere uova una alla volta.',
        'Aggiungere vaniglia e colorante. Unire latticello. Poi cacao e farina setacciati a bassa velocità.',
        'Mescolare aceto e bicarbonato, aggiungere con il sale.',
        'Stampo 24cm imburrato e infarinato. Forno statico 175° per 45-50 min.',
        'Crema: montare tutti gli ingredienti freddi in planetaria. Riposare in frigo 60 min.',
      ],
    },
    // ─── Granita alla mandorla ───
    {
      name: 'Granita alla mandorla',
      description: 'Granita siciliana alla mandorla.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 15,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes:
        'Alternativa: 200g mandorle pelate, 600ml acqua, 60g zucchero → frullare, filtrare, bollire 5 min, congelare 6-8h, frullare con mixer.\nhttps://www.facebook.com/share/r/1AXoi3G1bU/',
      tags: ['dolce', 'granita', 'mandorle', 'siciliano'],
      ingredients: [
        { name: 'Pasta di mandorle', qty: 250, unit: 'GRAM' },
        { name: 'Sale', qty: null, unit: null },
      ],
      steps: [
        'Sciogliere la pasta di mandorle in 500g di acqua. Aggiungere un pizzico di sale.',
        'Mettere in freezer mescolando ogni 30 minuti fino a consistenza granita.',
      ],
    },
    // ─── Cremino caffè ───
    {
      name: 'Cremino caffè',
      description: 'Crema al caffè fredda.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 15,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes: 'https://www.tavolartegusto.it/ricetta/crema-al-caffe/',
      tags: ['dolce', 'caffè'],
      ingredients: [
        { name: 'Panna per dolci', qty: 500, unit: 'MILLILITER' },
        { name: 'Caffè', qty: 80, unit: 'GRAM' },
        { name: 'Zucchero a velo', qty: 50, unit: 'GRAM' },
      ],
      steps: [],
    },
    // ─── Besciamella ───
    {
      name: 'Besciamella',
      description: 'Besciamella classica.',
      cuisine: 'ITALIAN',
      type: 'OTHER',
      difficulty: 'EASY',
      time_value: 10,
      time_unit: 'MINUTE',
      servings: 1,
      wip: false,
      notes: '',
      tags: ['salsa', 'base'],
      ingredients: [
        { name: 'Latte', qty: 100, unit: 'MILLILITER' },
        { name: 'Burro', qty: 10, unit: 'GRAM' },
        { name: 'Farina', qty: 10, unit: 'GRAM' },
        { name: 'Sale', qty: null, unit: null },
        { name: 'Noce moscata', qty: null, unit: null },
      ],
      steps: [],
    },
    // ─── Cheesecake ───
    {
      name: 'Cheesecake',
      description: 'Cheesecake fredda con salsa ai lamponi.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: 30,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes:
        'Versione stampo piccolo: 150g biscotti, 55g burro, 143g panna, 215g yogurt, 215g philadelphia, 72g zucchero a velo, 4g gelatina in 20g acqua.',
      tags: ['dolce', 'cheesecake'],
      ingredients: [
        { name: 'Biscotti digestive', qty: 275, unit: 'GRAM' },
        { name: 'Burro', qty: 100, unit: 'GRAM' },
        { name: 'Panna per dolci', qty: 250, unit: 'MILLILITER' },
        { name: 'Yogurt greco', qty: 375, unit: 'GRAM' },
        { name: 'Philadelphia', qty: 375, unit: 'GRAM' },
        { name: 'Zucchero a velo', qty: 125, unit: 'GRAM' },
        { name: 'Gelatina in fogli', qty: 6, unit: 'GRAM' },
        { name: 'Scorza di limone', qty: null, unit: null },
        { name: 'Lamponi', qty: 300, unit: 'GRAM' },
      ],
      steps: [
        'Frullare biscotti, unire burro fuso. Pressare sul fondo dello stampo.',
        'Ammollare gelatina (6g in 30g acqua) 10 minuti. Sciogliere in parte della panna calda.',
        'Montare restante panna. Unire philadelphia, zucchero a velo setacciato, scorza limone, yogurt greco e panna montata.',
        'Mescolare delicatamente la gelatina. Versare nello stampo. Frigo tutta la notte.',
        'Salsa: scaldare lamponi con acqua fino a rilascio succo. Aggiungere zucchero a velo e acqua a piacere.',
      ],
    },
    // ─── Torta Camilla ───
    {
      name: 'Torta Camilla',
      description: 'Torta alle carote tipo merendina del Mulino Bianco.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 45,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes: 'https://ricette.giallozafferano.it/Torta-Camilla.html',
      tags: ['dolce', 'carote'],
      ingredients: [
        { name: 'Carota', qty: 250, unit: 'GRAM' },
        { name: 'Farina', qty: 300, unit: 'GRAM' },
        { name: 'Farina di mandorle', qty: 120, unit: 'GRAM' },
        { name: 'Latte di mandorle', qty: 150, unit: 'MILLILITER' },
        { name: 'Zucchero', qty: 200, unit: 'GRAM' },
        { name: 'Uova', qty: 2, unit: 'PIECE' },
        { name: 'Olio di semi di girasole', qty: 100, unit: 'MILLILITER' },
        { name: 'Lievito per dolci', qty: 16, unit: 'GRAM' },
        { name: 'Scorza di arancia', qty: 1, unit: 'PIECE' },
        { name: 'Sale', qty: null, unit: null },
      ],
      steps: [],
    },
    // ─── Muffuletta ───
    {
      name: 'Muffuletta',
      description: 'Muffuletta palermitana con sesamo.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 6,
      wip: false,
      notes:
        'Impasto diretto il giorno prima.\nProvare versione più pane pizza: 250g farina pizzeria, 250g semola, 2-3g lievito fresco, 270g acqua, 30g olio, 8g sale, 5g malto.\nhttps://www.lacucinaditricchitrocchi.it/le-muffulette-palermitane/',
      tags: ['pane', 'siciliano', 'lievitati'],
      ingredients: [
        { name: 'Farina manitoba', qty: 250, unit: 'GRAM' },
        { name: 'Farina di semola', qty: 250, unit: 'GRAM' },
        { name: 'Lievito di birra fresco', qty: 3, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: 50, unit: 'MILLILITER' },
        { name: 'Sale', qty: 8, unit: 'GRAM' },
        { name: 'Zucchero', qty: 20, unit: 'GRAM' },
        { name: 'Malto in polvere', qty: 2.5, unit: 'GRAM' },
        { name: 'Semi di sesamo', qty: null, unit: null },
      ],
      steps: [],
    },
    // ─── Cioccolata al latte ───
    {
      name: 'Cioccolata al latte',
      description: 'Cioccolata calda al latte.',
      cuisine: 'ITALIAN',
      type: 'BEVERAGE',
      difficulty: 'EASY',
      time_value: 10,
      time_unit: 'MINUTE',
      servings: 2,
      wip: false,
      notes: '',
      tags: ['bevanda', 'cioccolato'],
      ingredients: [
        { name: 'Latte', qty: 450, unit: 'MILLILITER' },
        { name: 'Cioccolato al latte', qty: 100, unit: 'GRAM' },
        { name: 'Cacao amaro', qty: 20, unit: 'GRAM' },
        { name: 'Amido di riso', qty: 10, unit: 'GRAM' },
      ],
      steps: [],
    },
    // ─── Hamburger di ceci ───
    {
      name: 'Hamburger di ceci',
      description: 'Burger vegetale di ceci.',
      cuisine: 'ITALIAN',
      type: 'SECONDCOURSE',
      difficulty: 'EASY',
      time_value: 30,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes:
        'https://www.tavolartegusto.it/ricetta/hamburger-di-ceci/amp/\nhttps://ricette.giallozafferano.it/Hamburger-di-ceci.html',
      tags: ['secondo', 'vegetariano', 'ceci'],
      ingredients: [
        { name: 'Ceci', qty: 80, unit: 'GRAM' },
        { name: 'Pomodoro', qty: 90, unit: 'GRAM' },
        { name: 'Concentrato di pomodoro', qty: 24, unit: 'GRAM' },
        { name: 'Farina di ceci', qty: 40, unit: 'GRAM' },
        { name: 'Amido di riso', qty: 5, unit: 'GRAM' },
        { name: 'Olio di semi di girasole', qty: 30, unit: 'MILLILITER' },
        { name: 'Cipolla', qty: null, unit: null },
        { name: 'Semi di sesamo', qty: null, unit: null },
        { name: 'Sale', qty: null, unit: null },
        { name: 'Rosmarino', qty: null, unit: null },
      ],
      steps: [],
    },
    // ─── Torta caprese ───
    {
      name: 'Torta caprese',
      description: 'Torta caprese al cioccolato e mandorle.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: 45,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes: 'Meglio: https://www.tavolartegusto.it/ricetta/torta-caprese-la-ricetta-originale/',
      tags: ['dolce', 'cioccolato', 'mandorle', 'napoletano'],
      ingredients: [
        { name: 'Burro', qty: 200, unit: 'GRAM' },
        { name: 'Zucchero', qty: 300, unit: 'GRAM' },
        { name: 'Mandorla', qty: 300, unit: 'GRAM' },
        { name: 'Cioccolato fondente', qty: 200, unit: 'GRAM' },
        { name: 'Uova', qty: 6, unit: 'PIECE' },
        { name: 'Arancia', qty: 1, unit: 'PIECE' },
      ],
      steps: ['Forno 170°. Stampo 28-30cm.'],
    },
    // ─── Biscotti da tè ───
    {
      name: 'Biscotti da tè',
      description: '',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 20,
      wip: true,
      notes:
        'https://blog.giallozafferano.it/allacciateilgrembiule/biscotti-da-te/\nUsare zucchero a velo.',
      tags: ['dolce', 'biscotti'],
      ingredients: [],
      steps: [],
    },
    // ─── Torta al limone ───
    {
      name: 'Torta al limone',
      description: 'Torta soffice al limone.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 45,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes:
        'Con 2 uova provare: 90g zucchero, 170g farina, 60g olio, 50g acqua, 40g succo limone, 2-3 scorze, 10g lievito (o bicarbonato e aceto di mele).',
      tags: ['dolce', 'limone'],
      ingredients: [
        { name: 'Farina', qty: 250, unit: 'GRAM' },
        { name: 'Zucchero', qty: 200, unit: 'GRAM' },
        { name: 'Uova', qty: 3, unit: 'PIECE' },
        { name: 'Olio di semi di girasole', qty: 120, unit: 'MILLILITER' },
        { name: 'Succo di limone', qty: 100, unit: 'MILLILITER' },
        { name: 'Scorza di limone', qty: 2, unit: 'PIECE' },
        { name: 'Lievito per dolci', qty: 16, unit: 'GRAM' },
        { name: 'Sale', qty: null, unit: null },
      ],
      steps: ['180° per 45 min.'],
    },
    // ─── Pizza Tradizionale ───
    {
      name: 'Pizza Tradizionale',
      description: 'Pizza napoletana tradizionale.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 3,
      wip: false,
      notes: '',
      tags: ['pizza', 'napoletano'],
      ingredients: [
        { name: 'Farina 0', qty: 600, unit: 'GRAM' },
        { name: 'Lievito di birra fresco', qty: 1.2, unit: 'GRAM' },
        { name: 'Sale', qty: 18, unit: 'GRAM' },
      ],
      steps: [],
    },
    // ─── Panini hamburger ───
    {
      name: 'Panini hamburger',
      description: 'Burger buns fatti in casa.',
      cuisine: 'AMERICAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'EASY',
      time_value: 180,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes:
        'Per 2: dividi tutto per 4. Per 4 mini veg: 100g farina, 50g manitoba, 15g zucchero, 2g lievito secco, 8g olio, 20g acqua faba, 60g acqua, 2g sale.\nhttps://nonsolofood.com/burger-bun-finalmente-la-ricetta/\nProvare: https://www.cookergirl.com/recipe/burger-buns/',
      tags: ['pane', 'hamburger', 'lievitati'],
      ingredients: [
        { name: 'Farina', qty: 300, unit: 'GRAM' },
        { name: 'Farina manitoba', qty: 150, unit: 'GRAM' },
        { name: 'Zucchero', qty: 50, unit: 'GRAM' },
        { name: 'Lievito di birra secco', qty: 7, unit: 'GRAM' },
        { name: 'Burro', qty: 30, unit: 'GRAM' },
        { name: 'Uova', qty: 1, unit: 'PIECE' },
        { name: 'Sale', qty: 6, unit: 'GRAM' },
      ],
      steps: [
        'Lievitare 2h impasto intero, poi 1h divisi in panetti sulla teglia.',
        'Cottura 170° per 15 min.',
      ],
    },
    // ─── Tortino cuore caldo ───
    {
      name: 'Tortino cuore caldo',
      description: 'Tortino al cioccolato con cuore fondente.',
      cuisine: 'FRENCH',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: 20,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes: 'https://ricette.giallozafferano.it/Tortino-di-cioccolato-con-cuore-fondente.html',
      tags: ['dolce', 'cioccolato'],
      ingredients: [
        { name: 'Cioccolato fondente 70%', qty: 110, unit: 'GRAM' },
        { name: 'Burro', qty: 110, unit: 'GRAM' },
        { name: 'Uova', qty: 2, unit: 'PIECE' },
        { name: 'Zucchero', qty: 40, unit: 'GRAM' },
        { name: 'Farina', qty: 25, unit: 'GRAM' },
      ],
      steps: ['190° per 14-15 minuti.'],
    },
  ];

  // Insert recipes
  let count = 0;
  for (const r of recipes) {
    // Check for duplicates
    const existing = (await db.get(
      'SELECT id, wip FROM recipes WHERE user_id = ? AND name = ?',
      userId,
      r.name,
    )) as { id: string; wip: number } | undefined;

    let recipeId: string;

    if (existing && existing.wip && !r.wip) {
      // Upgrade existing WIP recipe to full recipe
      recipeId = existing.id;
      await db.run(
        `UPDATE recipes SET description=?, cuisine=?, type=?, difficulty=?, time_value=?, time_unit=?, servings=?, wip=?, notes=? WHERE id=?`,
        r.description,
        r.cuisine,
        r.type,
        r.difficulty,
        r.time_value,
        r.time_unit,
        r.servings,
        0,
        r.notes,
        recipeId,
      );
      // Remove old ingredients/steps/tags
      await db.run('DELETE FROM recipe_ingredients WHERE recipe_id = ?', recipeId);
      await db.run('DELETE FROM recipe_steps WHERE recipe_id = ?', recipeId);
      await db.run('DELETE FROM recipe_tags WHERE recipe_id = ?', recipeId);
      console.log(`  [UPD] ${r.name} (WIP → full recipe)`);
    } else if (existing) {
      console.log(`  [SKIP] ${r.name} (already exists)`);
      continue;
    } else {
      recipeId = uuid();
      await db.run(
        `INSERT INTO recipes (id, user_id, name, description, cuisine, type, difficulty, time_value, time_unit, servings, wip, notes)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        recipeId,
        userId,
        r.name,
        r.description,
        r.cuisine,
        r.type,
        r.difficulty,
        r.time_value,
        r.time_unit,
        r.servings,
        r.wip ? 1 : 0,
        r.notes,
      );
    }

    for (let i = 0; i < r.ingredients.length; i++) {
      const ing = r.ingredients[i];
      const food = findFood(ing.name);
      await db.run(
        `INSERT INTO recipe_ingredients (id, recipe_id, food_id, name, quantity_value, quantity_unit, sort_order)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
        uuid(),
        recipeId,
        food?.id || null,
        ing.name,
        ing.qty,
        ing.unit,
        i,
      );
    }

    for (let i = 0; i < r.steps.length; i++) {
      await db.run(
        `INSERT INTO recipe_steps (id, recipe_id, text, image_url, sort_order) VALUES (?, ?, ?, '', ?)`,
        uuid(),
        recipeId,
        r.steps[i],
        i,
      );
    }

    for (const tag of r.tags) {
      await db.run(
        'INSERT OR IGNORE INTO recipe_tags (recipe_id, tag) VALUES (?, ?)',
        recipeId,
        tag,
      );
    }

    count++;
    console.log(`  [${count}] ✓ ${r.name}${r.wip ? ' (WIP)' : ''}`);
  }

  console.log(`\nDone! Inserted ${count} recipes.`);
  process.exit(0);
}

main().catch((err) => {
  console.error('Error:', err);
  process.exit(1);
});
