/**
 * Bulk recipe import script.
 * Inserts recipes directly into the SQLite database.
 *
 * Usage:
 *   npx ts-node src/import-recipes.ts
 */

import crypto from 'crypto';
import { getDB, seedFoods } from './db';

const uuid = () => crypto.randomUUID();

interface RecipeInput {
  name: string;
  description: string;
  cuisine: string;
  type: string;
  difficulty: string;
  time_value: number | null;
  time_unit: string;
  servings: number;
  wip: boolean;
  notes: string;
  tags: string[];
  ingredients: { name: string; qty: number | null; unit: string | null }[];
  steps: string[];
}

async function main() {
  const db = await getDB();
  await seedFoods();

  // Find user — pick first user in db or create one
  let user = await db.get('SELECT id FROM users LIMIT 1');
  if (!user) {
    const userId = uuid();
    await db.run(
      `INSERT INTO users (id, name, email) VALUES (?, ?, ?)`,
      userId,
      'Fabiano',
      'fabiano@foodrecipes.app',
    );
    user = { id: userId };
  }
  const userId = user.id;
  console.log(`Using user: ${userId}`);

  // ── New foods to seed ─────────────────────────────────────────
  const newFoods: {
    id: string;
    name: string;
    name_it: string;
    unit: string;
    kcal: number;
    protein: number;
    fat: number;
    carbs: number;
    fiber: number;
  }[] = [
    {
      id: 'f100',
      name: 'Coconut flour',
      name_it: 'Farina di cocco',
      unit: 'GRAM',
      kcal: 443,
      protein: 19.3,
      fat: 14.7,
      carbs: 58.9,
      fiber: 39.0,
    },
    {
      id: 'f101',
      name: 'Cocoa powder',
      name_it: 'Cacao amaro',
      unit: 'GRAM',
      kcal: 228,
      protein: 19.6,
      fat: 13.7,
      carbs: 57.9,
      fiber: 33.2,
    },
    {
      id: 'f102',
      name: 'Baking powder',
      name_it: 'Lievito per dolci',
      unit: 'GRAM',
      kcal: 53,
      protein: 0.0,
      fat: 0.0,
      carbs: 27.7,
      fiber: 0.0,
    },
    {
      id: 'f103',
      name: 'Hazelnuts',
      name_it: 'Nocciole',
      unit: 'GRAM',
      kcal: 628,
      protein: 15.0,
      fat: 60.8,
      carbs: 16.7,
      fiber: 9.7,
    },
    {
      id: 'f104',
      name: 'Powdered sugar',
      name_it: 'Zucchero a velo',
      unit: 'GRAM',
      kcal: 389,
      protein: 0.0,
      fat: 0.0,
      carbs: 97.0,
      fiber: 0.0,
    },
    {
      id: 'f105',
      name: 'Seed oil',
      name_it: 'Olio di semi',
      unit: 'MILLILITER',
      kcal: 884,
      protein: 0.0,
      fat: 100.0,
      carbs: 0.0,
      fiber: 0.0,
    },
    {
      id: 'f106',
      name: 'Soy lecithin',
      name_it: 'Lecitina di soia',
      unit: 'GRAM',
      kcal: 763,
      protein: 0.0,
      fat: 97.0,
      carbs: 0.0,
      fiber: 0.0,
    },
    {
      id: 'f107',
      name: 'Vanilla',
      name_it: 'Vaniglia',
      unit: 'GRAM',
      kcal: 288,
      protein: 0.1,
      fat: 0.1,
      carbs: 12.7,
      fiber: 0.0,
    },
    {
      id: 'f108',
      name: 'Ground beef',
      name_it: 'Carne tritata',
      unit: 'GRAM',
      kcal: 250,
      protein: 26.1,
      fat: 17.0,
      carbs: 0.0,
      fiber: 0.0,
    },
    {
      id: 'f109',
      name: 'Breadcrumbs',
      name_it: 'Pangrattato',
      unit: 'GRAM',
      kcal: 395,
      protein: 13.4,
      fat: 5.3,
      carbs: 71.7,
      fiber: 4.5,
    },
    {
      id: 'f110',
      name: 'Mascarpone',
      name_it: 'Mascarpone',
      unit: 'GRAM',
      kcal: 460,
      protein: 4.8,
      fat: 47.0,
      carbs: 2.0,
      fiber: 0.0,
    },
    {
      id: 'f111',
      name: 'Whipping cream',
      name_it: 'Panna per dolci',
      unit: 'MILLILITER',
      kcal: 340,
      protein: 2.1,
      fat: 35.0,
      carbs: 3.7,
      fiber: 0.0,
    },
    {
      id: 'f112',
      name: 'Anelletti pasta',
      name_it: 'Anelletti',
      unit: 'GRAM',
      kcal: 158,
      protein: 5.8,
      fat: 0.9,
      carbs: 30.9,
      fiber: 2.5,
    },
    {
      id: 'f113',
      name: 'Béchamel',
      name_it: 'Besciamella',
      unit: 'MILLILITER',
      kcal: 120,
      protein: 3.5,
      fat: 8.0,
      carbs: 8.5,
      fiber: 0.0,
    },
    {
      id: 'f114',
      name: 'Baking soda',
      name_it: 'Bicarbonato',
      unit: 'GRAM',
      kcal: 0,
      protein: 0.0,
      fat: 0.0,
      carbs: 0.0,
      fiber: 0.0,
    },
    {
      id: 'f115',
      name: 'Almond extract',
      name_it: 'Aroma mandorla',
      unit: 'MILLILITER',
      kcal: 0,
      protein: 0.0,
      fat: 0.0,
      carbs: 0.0,
      fiber: 0.0,
    },
    {
      id: 'f116',
      name: 'Manitoba flour',
      name_it: 'Farina manitoba',
      unit: 'GRAM',
      kcal: 360,
      protein: 14.0,
      fat: 1.0,
      carbs: 72.0,
      fiber: 2.5,
    },
    {
      id: 'f117',
      name: 'Dry yeast',
      name_it: 'Lievito di birra secco',
      unit: 'GRAM',
      kcal: 325,
      protein: 40.0,
      fat: 7.6,
      carbs: 41.2,
      fiber: 26.9,
    },
    {
      id: 'f118',
      name: 'Cinnamon',
      name_it: 'Cannella',
      unit: 'GRAM',
      kcal: 247,
      protein: 4.0,
      fat: 1.2,
      carbs: 80.6,
      fiber: 53.1,
    },
    {
      id: 'f119',
      name: 'Pistachio paste',
      name_it: 'Pasta di pistacchi',
      unit: 'GRAM',
      kcal: 600,
      protein: 20.0,
      fat: 45.0,
      carbs: 28.0,
      fiber: 10.0,
    },
    {
      id: 'f120',
      name: 'Condensed milk',
      name_it: 'Latte condensato',
      unit: 'GRAM',
      kcal: 321,
      protein: 8.1,
      fat: 8.7,
      carbs: 55.5,
      fiber: 0.0,
    },
    {
      id: 'f121',
      name: 'Gelatin sheets',
      name_it: 'Gelatina in fogli',
      unit: 'GRAM',
      kcal: 335,
      protein: 84.0,
      fat: 0.0,
      carbs: 0.0,
      fiber: 0.0,
    },
    {
      id: 'f122',
      name: 'Sugar pearls',
      name_it: 'Granella di zucchero',
      unit: 'GRAM',
      kcal: 387,
      protein: 0.0,
      fat: 0.0,
      carbs: 100.0,
      fiber: 0.0,
    },
    {
      id: 'f123',
      name: 'Vanilla extract',
      name_it: 'Estratto di vaniglia',
      unit: 'MILLILITER',
      kcal: 288,
      protein: 0.1,
      fat: 0.1,
      carbs: 12.7,
      fiber: 0.0,
    },
    {
      id: 'f124',
      name: 'Peanut butter',
      name_it: "Burro d'arachidi",
      unit: 'GRAM',
      kcal: 598,
      protein: 22.2,
      fat: 51.4,
      carbs: 22.3,
      fiber: 6.0,
    },
    {
      id: 'f125',
      name: 'Brown cane sugar',
      name_it: 'Zucchero grezzo di canna',
      unit: 'GRAM',
      kcal: 380,
      protein: 0.0,
      fat: 0.0,
      carbs: 98.0,
      fiber: 0.0,
    },
    {
      id: 'f126',
      name: 'Lard',
      name_it: 'Strutto',
      unit: 'GRAM',
      kcal: 902,
      protein: 0.0,
      fat: 100.0,
      carbs: 0.0,
      fiber: 0.0,
    },
    {
      id: 'f127',
      name: 'Nutmeg',
      name_it: 'Noce moscata',
      unit: 'GRAM',
      kcal: 525,
      protein: 5.8,
      fat: 36.3,
      carbs: 49.3,
      fiber: 20.8,
    },
    {
      id: 'f128',
      name: 'Grana Padano',
      name_it: 'Grana padano',
      unit: 'GRAM',
      kcal: 392,
      protein: 33.0,
      fat: 28.0,
      carbs: 0.0,
      fiber: 0.0,
    },
    {
      id: 'f129',
      name: 'Flour type 0',
      name_it: 'Farina 0',
      unit: 'GRAM',
      kcal: 364,
      protein: 10.3,
      fat: 1.0,
      carbs: 76.3,
      fiber: 2.7,
    },
    {
      id: 'f130',
      name: 'Malted barley',
      name_it: 'Malto in polvere',
      unit: 'GRAM',
      kcal: 361,
      protein: 10.3,
      fat: 1.8,
      carbs: 78.3,
      fiber: 0.0,
    },
    {
      id: 'f131',
      name: 'Strong flour W300',
      name_it: 'Farina W300-320',
      unit: 'GRAM',
      kcal: 364,
      protein: 13.5,
      fat: 1.0,
      carbs: 72.0,
      fiber: 2.7,
    },
    {
      id: 'f132',
      name: 'Lentils',
      name_it: 'Lenticchie',
      unit: 'GRAM',
      kcal: 116,
      protein: 9.0,
      fat: 0.4,
      carbs: 20.1,
      fiber: 7.9,
    },
    {
      id: 'f133',
      name: 'Parsley',
      name_it: 'Prezzemolo',
      unit: 'GRAM',
      kcal: 36,
      protein: 3.0,
      fat: 0.8,
      carbs: 6.3,
      fiber: 3.3,
    },
    {
      id: 'f134',
      name: 'Egg whites',
      name_it: 'Albumi',
      unit: 'GRAM',
      kcal: 52,
      protein: 10.9,
      fat: 0.2,
      carbs: 0.7,
      fiber: 0.0,
    },
    {
      id: 'f135',
      name: 'Rice starch',
      name_it: 'Amido di riso',
      unit: 'GRAM',
      kcal: 381,
      protein: 0.0,
      fat: 0.0,
      carbs: 94.0,
      fiber: 0.0,
    },
    {
      id: 'f136',
      name: 'Vanillin',
      name_it: 'Vanillina',
      unit: 'PIECE',
      kcal: 0,
      protein: 0.0,
      fat: 0.0,
      carbs: 0.0,
      fiber: 0.0,
    },
    {
      id: 'f137',
      name: 'Brown sugar',
      name_it: 'Zucchero di canna',
      unit: 'GRAM',
      kcal: 380,
      protein: 0.0,
      fat: 0.0,
      carbs: 98.0,
      fiber: 0.0,
    },
  ];

  const foodStmt = await db.prepare(
    `INSERT INTO foods (id, name, name_it, default_unit, kcal, protein, fat, carbs, fiber)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(id) DO UPDATE SET name_it=excluded.name_it, kcal=excluded.kcal, protein=excluded.protein, fat=excluded.fat, carbs=excluded.carbs, fiber=excluded.fiber`,
  );
  for (const f of newFoods) {
    await foodStmt.run(f.id, f.name, f.name_it, f.unit, f.kcal, f.protein, f.fat, f.carbs, f.fiber);
  }
  await foodStmt.finalize();
  console.log(`Seeded ${newFoods.length} new foods.`);

  // Build a lookup map: Italian food name -> food id (case-insensitive)
  const allFoods = await db.all('SELECT id, name, name_it, default_unit FROM foods');
  const foodMap = new Map<string, { id: string; unit: string }>();
  for (const f of allFoods) {
    if (f.name_it) foodMap.set(f.name_it.toLowerCase(), { id: f.id, unit: f.default_unit });
    if (f.name) foodMap.set(f.name.toLowerCase(), { id: f.id, unit: f.default_unit });
  }

  // Helper to look up a food and try common aliases
  function findFood(name: string): { id: string; unit: string } | undefined {
    const n = name.toLowerCase().trim();
    if (foodMap.has(n)) return foodMap.get(n);
    // Try partial matches
    for (const [key, val] of foodMap) {
      if (n.includes(key) || key.includes(n)) return val;
    }
    return undefined;
  }

  // ── Recipes ────────────────────────────────────────────────────
  const recipes: RecipeInput[] = [
    {
      name: 'Torta cioccolato e cocco',
      description: 'Torta soffice al cioccolato con farina di cocco.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 45,
      time_unit: 'MINUTE',
      servings: 6,
      wip: false,
      notes: '',
      tags: ['dolce', 'cioccolato', 'cocco'],
      ingredients: [
        { name: 'Uova', qty: 3, unit: 'PIECE' },
        { name: 'Farina di cocco', qty: 115, unit: 'GRAM' },
        { name: 'Zucchero', qty: 110, unit: 'GRAM' },
        { name: 'Farina', qty: 40, unit: 'GRAM' },
        { name: 'Cacao amaro', qty: 35, unit: 'GRAM' },
        { name: 'Latte', qty: 90, unit: 'MILLILITER' },
        { name: 'Burro', qty: 90, unit: 'GRAM' },
        { name: 'Lievito per dolci', qty: 10, unit: 'GRAM' },
      ],
      steps: [],
    },
    {
      name: 'Nutella fatta in casa',
      description: 'Crema spalmabile alle nocciole fatta in casa.',
      cuisine: 'ITALIAN',
      type: 'OTHER',
      difficulty: 'MEDIUM',
      time_value: 30,
      time_unit: 'MINUTE',
      servings: 10,
      wip: false,
      notes: '',
      tags: ['dolce', 'crema', 'nocciole'],
      ingredients: [
        { name: 'Nocciole', qty: 500, unit: 'GRAM' },
        { name: 'Zucchero a velo', qty: 350, unit: 'GRAM' },
        { name: 'Cacao amaro', qty: 100, unit: 'GRAM' },
        { name: 'Olio di semi', qty: 120, unit: 'MILLILITER' },
        { name: 'Lecitina di soia', qty: 5, unit: 'GRAM' },
        { name: 'Sale', qty: 2, unit: 'GRAM' },
        { name: 'Vaniglia', qty: 1, unit: 'GRAM' },
      ],
      steps: [],
    },
    {
      name: 'Focaccia patate',
      description: '',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes: 'https://www.instagram.com/reel/CQx0cx8J6_E/?utm_medium=copy_link',
      tags: ['focaccia', 'patate', 'lievitati'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Panettone',
      description: '',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'HARD',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 8,
      wip: true,
      notes:
        'Per il procedimento con lievito madre disidratato: https://blog.giallozafferano.it/giustopergusto/panettone-con-madre-disidratato/\nPer mix aromatico e taglio: https://www.tavolartegusto.it/ricetta/ricetta-panettone-fatto-in-casa/',
      tags: ['dolce', 'natale', 'lievitati'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Cassata al forno',
      description: '',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'HARD',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 8,
      wip: true,
      notes: 'https://www.tavolartegusto.it/ricetta/cassata-al-forno-siciliana/amp/',
      tags: ['dolce', 'siciliano'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Pasta biscotto',
      description: '',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes: 'https://ricette.giallozafferano.it/Pasta-biscotto.html',
      tags: ['dolce', 'base'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Pasta sfoglia',
      description: '',
      cuisine: 'ITALIAN',
      type: 'OTHER',
      difficulty: 'HARD',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes: 'https://ricette.giallozafferano.it/Pasta-Sfoglia.html',
      tags: ['base', 'lievitati'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Mini Plum cake',
      description: '',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 12,
      wip: true,
      notes: 'https://ricette.giallozafferano.it/Mini-plumcake-allo-yogurt.html',
      tags: ['dolce', 'colazione'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Graffa',
      description: '',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 8,
      wip: true,
      notes: 'https://vm.tiktok.com/ZMLHovvsP/',
      tags: ['dolce', 'fritto', 'napoletano'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Polpette',
      description: 'Polpette classiche con carne tritata.',
      cuisine: 'ITALIAN',
      type: 'SECONDCOURSE',
      difficulty: 'EASY',
      time_value: 30,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes: "N.B: Bagnare la mollica con dell'acqua prima di mescolare tutti gli ingredienti.",
      tags: ['secondo', 'carne'],
      ingredients: [
        { name: 'Carne tritata', qty: 300, unit: 'GRAM' },
        { name: 'Uova', qty: 1, unit: 'PIECE' },
        { name: 'Pangrattato', qty: 45, unit: 'GRAM' },
        { name: 'Formaggio', qty: 15, unit: 'GRAM' },
        { name: 'Cipolla', qty: null, unit: null },
        { name: 'Sale', qty: null, unit: null },
      ],
      steps: [
        "Bagnare la mollica con dell'acqua.",
        'Mescolare tutti gli ingredienti insieme.',
        'Formare le polpette e cuocere.',
      ],
    },
    {
      name: 'Torta Brownies',
      description: 'Brownies al cioccolato fondente con copertura.',
      cuisine: 'AMERICAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 30,
      time_unit: 'MINUTE',
      servings: 6,
      wip: false,
      notes: '',
      tags: ['dolce', 'cioccolato', 'americano'],
      ingredients: [
        { name: 'Burro', qty: 125, unit: 'GRAM' },
        { name: 'Uova', qty: 4, unit: 'PIECE' },
        { name: 'Farina', qty: 60, unit: 'GRAM' },
        { name: 'Zucchero', qty: 200, unit: 'GRAM' },
        { name: 'Cioccolato fondente', qty: 200, unit: 'GRAM' },
        { name: 'Cioccolato fondente', qty: 150, unit: 'GRAM' },
      ],
      steps: [
        'Sciogliere cioccolato e burro e fare raffreddare.',
        'Montare a neve gli albumi.',
        'Lavorare lo zucchero con i tuorli e poi unire il cioccolato fuso, la farina setacciata ed infine gli albumi.',
        'Cuocere a 180° per 30 min.',
        'Fare raffreddare, coprire e decorare con il cioccolato fuso.',
      ],
    },
    {
      name: 'Torta bigusto semplice',
      description: 'Torta metà chiara e metà al cioccolato con copertura.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 30,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes:
        "Il segreto è il forno freddo: mettere in forno e accendere a 180 gradi per più o meno mezz'ora (prova stecchino).",
      tags: ['dolce', 'cioccolato'],
      ingredients: [
        { name: 'Farina', qty: 300, unit: 'GRAM' },
        { name: 'Zucchero', qty: 250, unit: 'GRAM' },
        { name: 'Uova', qty: 3, unit: 'PIECE' },
        { name: 'Latte', qty: 200, unit: 'MILLILITER' },
        { name: 'Olio di semi', qty: 200, unit: 'MILLILITER' },
        { name: 'Lievito per dolci', qty: 16, unit: 'GRAM' },
        { name: 'Vanillina', qty: 1, unit: 'PIECE' },
        { name: 'Arancia', qty: 1, unit: 'PIECE' },
        { name: 'Cioccolato fondente', qty: 150, unit: 'GRAM' },
        { name: 'Cioccolato fondente', qty: 150, unit: 'GRAM' },
      ],
      steps: [
        "Mescolare farina, zucchero, uova, latte, olio, lievito, vanillina e succo d'arancia.",
        "Dividere l'impasto in due.",
        'In uno aggiungere il cioccolato fondente sciolto al microonde.',
        "Mettere in forno FREDDO e accendere a 180° per circa mezz'ora (prova stecchino).",
        'Fare raffreddare, coprire e decorare con il cioccolato fuso.',
      ],
    },
    {
      name: 'Crema degli angeli',
      description: 'Crema leggera con mascarpone e panna montata.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 15,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes: '',
      tags: ['dolce', 'crema', 'base'],
      ingredients: [
        { name: 'Mascarpone', qty: 250, unit: 'GRAM' },
        { name: 'Panna per dolci', qty: 150, unit: 'MILLILITER' },
        { name: 'Zucchero a velo', qty: 80, unit: 'GRAM' },
        { name: 'Vaniglia', qty: null, unit: null },
      ],
      steps: [
        'Mescolare mascarpone, zucchero a velo e vaniglia.',
        'A parte montare la panna.',
        'Amalgamare insieme al resto delicatamente.',
      ],
    },
    {
      name: 'Pasta al forno',
      description: 'Anelletti al forno con ragù e besciamella.',
      cuisine: 'ITALIAN',
      type: 'FIRSTCOURSE',
      difficulty: 'MEDIUM',
      time_value: 90,
      time_unit: 'MINUTE',
      servings: 3,
      wip: false,
      notes:
        'Usare la ricetta della besciamella come riferimento per la quantità. Aggiungere il pizzico di bicarbonato a metà cottura del ragù.',
      tags: ['primo', 'forno', 'ragù'],
      ingredients: [
        { name: 'Pomodoro', qty: 500, unit: 'GRAM' },
        { name: 'Carne tritata', qty: 200, unit: 'GRAM' },
        { name: 'Carota', qty: 0.5, unit: 'PIECE' },
        { name: 'Cipolla', qty: 0.5, unit: 'PIECE' },
        { name: "Olio d'oliva", qty: null, unit: null },
        { name: 'Sale', qty: null, unit: null },
        { name: 'Pepe nero', qty: null, unit: null },
        { name: 'Bicarbonato', qty: null, unit: null },
        { name: 'Anelletti', qty: 300, unit: 'GRAM' },
        { name: 'Besciamella', qty: 250, unit: 'MILLILITER' },
      ],
      steps: [
        'Preparare il ragù con pomodoro, tritato, carota e cipolla. Cucinare 1 ora.',
        'Aggiungere il pizzico di bicarbonato a metà cottura.',
        'Cucinare gli anelletti al dente.',
        'Mescolare con metà ragù e metà besciamella.',
        'Coprire con una spolverata di parmigiano.',
        'Cucinare 20 min a 160° statico, poi 5 min a 160° ventilato.',
      ],
    },
    {
      name: 'Torta cocco',
      description: 'Torta al cocco con cacao e crema degli angeli.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 40,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes: 'Usare la ricetta della Crema degli angeli per la copertura.',
      tags: ['dolce', 'cocco', 'cioccolato'],
      ingredients: [
        { name: 'Farina di cocco', qty: 75, unit: 'GRAM' },
        { name: 'Zucchero', qty: 75, unit: 'GRAM' },
        { name: 'Farina', qty: 25, unit: 'GRAM' },
        { name: 'Cacao amaro', qty: 25, unit: 'GRAM' },
        { name: 'Uova', qty: 2, unit: 'PIECE' },
        { name: 'Latte', qty: 62.5, unit: 'MILLILITER' },
        { name: 'Burro', qty: 62.5, unit: 'GRAM' },
        { name: 'Lievito per dolci', qty: 8, unit: 'GRAM' },
      ],
      steps: [
        'Mettere in una ciotola il burro morbido e lo zucchero e lavorarli con lo sbattitore elettrico fino ad ottenere una crema.',
        'Aggiungere le uova una alla volta.',
        'Aggiungere la farina setacciata insieme al lievito e al cacao. Lavorare e infine unire il latte e il cocco.',
        'Forno statico preriscaldato 180°, 35-40 min.',
      ],
    },
    {
      name: 'Parfait di mandorla',
      description: 'Semifreddo alle mandorle pralinate con copertura al fondente.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'HARD',
      time_value: 60,
      time_unit: 'MINUTE',
      servings: 6,
      wip: false,
      notes: '',
      tags: ['dolce', 'mandorle', 'semifreddo'],
      ingredients: [
        { name: 'Cioccolato fondente', qty: 100, unit: 'GRAM' },
        { name: 'Panna per dolci', qty: 600, unit: 'MILLILITER' },
        { name: 'Aroma mandorla', qty: 1, unit: 'PIECE' },
        { name: 'Mandorla', qty: 200, unit: 'GRAM' },
        { name: 'Uova', qty: 2, unit: 'PIECE' },
        { name: 'Zucchero', qty: 200, unit: 'GRAM' },
      ],
      steps: [
        'Tritare le mandorle, unire 100g di zucchero e 2 cucchiai di acqua e pralinarle. Fare raffreddare.',
        'Montare la panna e mettere in frigo.',
        'Montare tuorli con 50g di zucchero e albumi con un pizzico di sale.',
        'Scaldare 25g di acqua con restante 50g di zucchero, portare a bollore e pastorizzare tuorli e albumi entrambi già montati.',
        "Unire il tutto alla panna aromatizzata con l'aroma mandorla, tenere da parte un po' di mandorle per decorare e mettere in freezer.",
        'Sciogliere la cioccolata e versarla sopra prima di servire.',
      ],
    },
    {
      name: 'Cinnamon Rolls',
      description: 'Girelle alla cannella con glassa di zucchero.',
      cuisine: 'AMERICAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: 240,
      time_unit: 'MINUTE',
      servings: 18,
      wip: false,
      notes: '',
      tags: ['dolce', 'lievitati', 'cannella', 'colazione'],
      ingredients: [
        { name: 'Farina manitoba', qty: 600, unit: 'GRAM' },
        { name: 'Lievito di birra secco', qty: 3, unit: 'GRAM' },
        { name: 'Latte', qty: 130, unit: 'MILLILITER' },
        { name: 'Zucchero', qty: 60, unit: 'GRAM' },
        { name: 'Burro', qty: 80, unit: 'GRAM' },
        { name: 'Uova', qty: 1, unit: 'PIECE' },
        { name: 'Sale', qty: 8, unit: 'GRAM' },
        { name: 'Burro', qty: 30, unit: 'GRAM' },
        { name: 'Zucchero', qty: 120, unit: 'GRAM' },
        { name: 'Cannella', qty: 10, unit: 'GRAM' },
        { name: 'Zucchero a velo', qty: 150, unit: 'GRAM' },
      ],
      steps: [
        'Preparare un lievitino mescolando lievito, 100g di farina e 100g di acqua+latte. Lasciar lievitare 2h.',
        'Unire al lievitino il resto della farina, zucchero, acqua e latte. Impastare, aggiungere uovo, poi burro a pezzetti e sale.',
        'Lievitare 3-4 ore fino al triplo.',
        "Stendere l'impasto a 1cm, rettangolo 50-55cm x 35-40cm.",
        'Pennellare con burro fuso, cospargere con zucchero e cannella mescolati.',
        'Arrotolare stretto dal lato lungo. Tagliare a fette di 2.5-3cm.',
        'Posizionare in teglia a 1cm di distanza. Lievitare 1 ora.',
        'Cuocere a 180° statico per 25 minuti.',
        'Raffreddare completamente. Glassare con zucchero a velo e acqua.',
      ],
    },
    {
      name: 'Torta Pistacchio e Galak',
      description: 'Cheesecake al pistacchio con base biscotto.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: 30,
      time_unit: 'MINUTE',
      servings: 6,
      wip: false,
      notes: '',
      tags: ['dolce', 'pistacchio', 'cheesecake'],
      ingredients: [
        { name: 'Panna per dolci', qty: 250, unit: 'MILLILITER' },
        { name: 'Latte condensato', qty: 80, unit: 'GRAM' },
        { name: 'Pasta di pistacchi', qty: 55, unit: 'GRAM' },
        { name: 'Gelatina in fogli', qty: 2, unit: 'GRAM' },
        { name: 'Sale', qty: null, unit: null },
      ],
      steps: [
        'Frullare i biscotti, aggiungere cannella, buccia di limone e zucchero di canna. Unire il burro fuso e pressare nei barattolini.',
        'Mettere la gelatina in ammollo in acqua fredda per 5-10 minuti.',
        'Scaldare la panna fresca fino a sfiorare il bollore, spegnere il fuoco, scolate la gelatina, strizzarla e aggiungerla alla panna calda.',
        'Mescolare con una frusta, aggiungere il latte condensato, poi la pasta di pistacchio e un pizzico di sale.',
      ],
    },
    {
      name: 'Waffle',
      description: 'Waffle belgi con granella di zucchero.',
      cuisine: 'FRENCH',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: 120,
      time_unit: 'MINUTE',
      servings: 8,
      wip: false,
      notes: '',
      tags: ['dolce', 'colazione', 'waffle'],
      ingredients: [
        { name: 'Farina', qty: 500, unit: 'GRAM' },
        { name: 'Burro', qty: 200, unit: 'GRAM' },
        { name: 'Sale', qty: 3, unit: 'GRAM' },
        { name: 'Zucchero di canna', qty: 40, unit: 'GRAM' },
        { name: 'Latte', qty: 200, unit: 'MILLILITER' },
        { name: 'Uova', qty: 2, unit: 'PIECE' },
        { name: 'Lievito di birra secco', qty: 6, unit: 'GRAM' },
        { name: 'Granella di zucchero', qty: 150, unit: 'GRAM' },
        { name: 'Estratto di vaniglia', qty: null, unit: null },
      ],
      steps: [
        "Ammorbidire il burro 2 ore prima di preparare l'impasto.",
        'Scaldare leggermente e diluire il lievito. Aggiungere farina, zucchero di canna e uova.',
        'Impastare per 5 minuti a velocità bassa. Aggiungere burro e sale, impastare 10 minuti.',
        'Lasciar lievitare 1h30.',
        "Aggiungere la granella di zucchero degassando l'impasto.",
        'Porzionare da 100g, riposare 20 minuti oppure 5-6 ore in frigo.',
      ],
    },
    {
      name: "Biscotti burro d'arachidi",
      description: 'Biscotti croccanti al burro di arachidi.',
      cuisine: 'AMERICAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 20,
      time_unit: 'MINUTE',
      servings: 20,
      wip: false,
      notes: '',
      tags: ['dolce', 'biscotti', 'arachidi'],
      ingredients: [
        { name: 'Farina', qty: 220, unit: 'GRAM' },
        { name: 'Burro', qty: 110, unit: 'GRAM' },
        { name: "Burro d'arachidi", qty: 110, unit: 'GRAM' },
        { name: 'Uova', qty: 1, unit: 'PIECE' },
        { name: 'Zucchero', qty: 70, unit: 'GRAM' },
        { name: 'Zucchero grezzo di canna', qty: 70, unit: 'GRAM' },
        { name: 'Sale', qty: 5, unit: 'GRAM' },
        { name: 'Bicarbonato', qty: 1, unit: 'GRAM' },
      ],
      steps: [
        'Amalgamare burro, zucchero, zucchero grezzo di canna, sale e burro di arachidi per un minuto fino a crema spumosa.',
        "Incorporare l'uovo fino ad assorbimento completo.",
        'Aggiungere farina setacciata con bicarbonato e lavorare pochissimo.',
        'Avvolgere nella pellicola e riposare in frigo 60 minuti.',
        'Formare palline e dare forma desiderata.',
        'Infornare a 180°C per circa 20 minuti.',
      ],
    },
    {
      name: 'Piadina romagnola',
      description: 'Piadina tradizionale romagnola con strutto.',
      cuisine: 'ITALIAN',
      type: 'OTHER',
      difficulty: 'EASY',
      time_value: 30,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes: '',
      tags: ['piadina', 'romagnola'],
      ingredients: [
        { name: 'Farina 0', qty: 250, unit: 'GRAM' },
        { name: 'Latte', qty: 125, unit: 'MILLILITER' },
        { name: 'Strutto', qty: 40, unit: 'GRAM' },
        { name: 'Bicarbonato', qty: null, unit: null },
        { name: 'Sale', qty: 6, unit: 'GRAM' },
      ],
      steps: [
        'Amalgamare il tutto e far riposare per 15 minuti.',
        'Dividere in panetti e spianarli con il matterello.',
        'Cuocere a fiamma medio/bassa.',
      ],
    },
    {
      name: 'Patate al forno',
      description: '',
      cuisine: 'ITALIAN',
      type: 'SIDE',
      difficulty: 'EASY',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes: '',
      tags: ['contorno', 'patate'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Purè di patate',
      description: 'Purè classico con latte e burro.',
      cuisine: 'ITALIAN',
      type: 'SIDE',
      difficulty: 'EASY',
      time_value: 40,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes: '',
      tags: ['contorno', 'patate'],
      ingredients: [
        { name: 'Patata', qty: 1000, unit: 'GRAM' },
        { name: 'Latte', qty: 250, unit: 'MILLILITER' },
        { name: 'Burro', qty: 50, unit: 'GRAM' },
        { name: 'Sale', qty: null, unit: null },
        { name: 'Noce moscata', qty: null, unit: null },
        { name: 'Grana padano', qty: null, unit: null },
      ],
      steps: [
        'Bollire le patate.',
        'Passarle a setaccio e mescolare tutti gli altri ingredienti accendendo il fuoco basso per amalgamare il tutto ottenendo la consistenza desiderata.',
      ],
    },
    {
      name: 'Pasta crema acciughe',
      description: '',
      cuisine: 'ITALIAN',
      type: 'FIRSTCOURSE',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes: 'https://www.instagram.com/reel/CeolXesFOUL/?igshid=YmMyMTA2M2Y=',
      tags: ['primo', 'pesce'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Fiocchi di patate',
      description: 'Cipster fatte in casa.',
      cuisine: 'ITALIAN',
      type: 'OTHER',
      difficulty: 'MEDIUM',
      time_value: null,
      time_unit: 'MINUTE',
      servings: 4,
      wip: true,
      notes: 'https://www.ilclubdellericette.it/ricetta/cipster-fatte-in-casa',
      tags: ['snack', 'patate'],
      ingredients: [],
      steps: [],
    },
    {
      name: 'Granita pistacchio',
      description: 'Granita al pistacchio siciliana.',
      cuisine: 'ITALIAN',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 15,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes: '',
      tags: ['dolce', 'pistacchio', 'granita', 'siciliano'],
      ingredients: [
        { name: 'Latte', qty: 300, unit: 'MILLILITER' },
        { name: 'Zucchero', qty: 80, unit: 'GRAM' },
        { name: 'Pasta di pistacchi', qty: 100, unit: 'GRAM' },
      ],
      steps: [
        'Mescolare acqua/latte, zucchero e pasta di pistacchio.',
        'Mettere in freezer mescolando ogni 30 minuti fino a consistenza granita.',
      ],
    },
    {
      name: 'Focaccia ligure',
      description: 'Focaccia genovese con salamoia.',
      cuisine: 'ITALIAN',
      type: 'YEASTPRODUCTS',
      difficulty: 'MEDIUM',
      time_value: 180,
      time_unit: 'MINUTE',
      servings: 6,
      wip: false,
      notes: '',
      tags: ['focaccia', 'lievitati', 'genovese'],
      ingredients: [
        { name: 'Farina W300-320', qty: 350, unit: 'GRAM' },
        { name: 'Lievito di birra secco', qty: 2, unit: 'GRAM' },
        { name: 'Malto in polvere', qty: 3, unit: 'GRAM' },
        { name: 'Sale', qty: 7, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: 15, unit: 'MILLILITER' },
        { name: "Olio d'oliva", qty: 25, unit: 'MILLILITER' },
        { name: 'Sale', qty: 5, unit: 'GRAM' },
      ],
      steps: [
        'Mettere in planetaria la farina, il malto ed il lievito secco.',
        "Azionare la planetaria e aggiungere quasi tutta l'acqua (210g, tenere 20-30g da parte).",
        "Quando la massa prende consistenza aggiungere il sale con l'ultima parte di acqua.",
        "Chiudere l'impasto con l'olio EVO a filo. L'impasto è pronto quando si stacca dai bordi.",
        'Lavorare sul banco per qualche minuto, coprire e far riposare 30 minuti.',
        'Stendere con dita e mattarello nella forma della teglia. Posizionare in teglia oliata.',
        'Coprire e lievitare 2 ore.',
        'Schiacciare i bordi e fare i classici buchi della focaccia genovese.',
        'Preparare la salamoia: 25g olio + 50g acqua + 5g sale (frullare). Versare sulla superficie.',
        'Riposare 30 minuti. Infornare a 250° per 15-20 minuti.',
      ],
    },
    {
      name: 'Hamburger vegetale',
      description: 'Burger di lenticchie con verdure.',
      cuisine: 'ITALIAN',
      type: 'SECONDCOURSE',
      difficulty: 'EASY',
      time_value: 30,
      time_unit: 'MINUTE',
      servings: 4,
      wip: false,
      notes: '',
      tags: ['secondo', 'vegetariano', 'lenticchie'],
      ingredients: [
        { name: 'Lenticchie', qty: 100, unit: 'GRAM' },
        { name: 'Carota', qty: 75, unit: 'GRAM' },
        { name: 'Zucchina', qty: 75, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: 15, unit: 'MILLILITER' },
        { name: 'Prezzemolo', qty: null, unit: null },
        { name: 'Sale', qty: null, unit: null },
        { name: 'Pepe nero', qty: null, unit: null },
      ],
      steps: [],
    },
    {
      name: 'Crêpes',
      description: 'Crêpes classiche francesi.',
      cuisine: 'FRENCH',
      type: 'DESSERT',
      difficulty: 'EASY',
      time_value: 20,
      time_unit: 'MINUTE',
      servings: 14,
      wip: false,
      notes: 'Per 1 porzione: 1 uovo, 83.3g farina, 166.6g latte, 13.3g burro.',
      tags: ['dolce', 'colazione', 'crepes'],
      ingredients: [
        { name: 'Uova', qty: 3, unit: 'PIECE' },
        { name: 'Farina', qty: 250, unit: 'GRAM' },
        { name: 'Latte', qty: 500, unit: 'MILLILITER' },
        { name: 'Burro', qty: 40, unit: 'GRAM' },
      ],
      steps: [],
    },
    {
      name: 'Biscotti della fortuna',
      description: 'Fortune cookies fatti in casa.',
      cuisine: 'CHINESE',
      type: 'DESSERT',
      difficulty: 'MEDIUM',
      time_value: 30,
      time_unit: 'MINUTE',
      servings: 10,
      wip: false,
      notes: '',
      tags: ['dolce', 'biscotti', 'cinese'],
      ingredients: [
        { name: 'Albumi', qty: 20, unit: 'GRAM' },
        { name: 'Zucchero', qty: 30, unit: 'GRAM' },
        { name: "Olio d'oliva", qty: 4, unit: 'MILLILITER' },
        { name: 'Farina', qty: 25, unit: 'GRAM' },
        { name: 'Amido di riso', qty: 3.5, unit: 'GRAM' },
        { name: 'Estratto di vaniglia', qty: 4, unit: 'MILLILITER' },
      ],
      steps: [
        'Sbattere albumi e zucchero con una frusta senza montarli. Aggiungere olio e vaniglia.',
        "Unire farina di riso, maizena e farina 00 setacciate. Lavorare fino ad amalgamare, aggiungere un goccio d'acqua.",
        'Forno statico a 170°. Su teglia con carta forno, versare cucchiai di impasto formando cerchi da 10cm.',
        'Infornare per circa 10 minuti finché il bordo è dorato.',
        'Sfornare, girare, posizionare il bigliettino al centro, piegare a metà e modellare a mezzaluna.',
        'Mettere nei stampini muffin per mantenere la forma e lasciar raffreddare.',
      ],
    },
  ];

  // Insert recipes
  let count = 0;
  for (const r of recipes) {
    const recipeId = uuid();
    await db.run(
      `INSERT INTO recipes (id, user_id, name, description, cuisine, type, difficulty, time_value, time_unit, servings, wip, notes)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      recipeId,
      userId,
      r.name,
      r.description,
      r.cuisine,
      r.type,
      r.difficulty,
      r.time_value,
      r.time_unit,
      r.servings,
      r.wip ? 1 : 0,
      r.notes,
    );

    // Insert ingredients
    for (let i = 0; i < r.ingredients.length; i++) {
      const ing = r.ingredients[i];
      const food = findFood(ing.name);
      await db.run(
        `INSERT INTO recipe_ingredients (id, recipe_id, food_id, name, quantity_value, quantity_unit, sort_order)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
        uuid(),
        recipeId,
        food?.id || null,
        ing.name,
        ing.qty,
        ing.unit,
        i,
      );
    }

    // Insert steps
    for (let i = 0; i < r.steps.length; i++) {
      await db.run(
        `INSERT INTO recipe_steps (id, recipe_id, text, image_url, sort_order)
         VALUES (?, ?, ?, '', ?)`,
        uuid(),
        recipeId,
        r.steps[i],
        i,
      );
    }

    // Insert tags
    for (const tag of r.tags) {
      await db.run(
        'INSERT OR IGNORE INTO recipe_tags (recipe_id, tag) VALUES (?, ?)',
        recipeId,
        tag,
      );
    }

    count++;
    console.log(`  [${count}/${recipes.length}] ✓ ${r.name}${r.wip ? ' (WIP)' : ''}`);
  }

  console.log(`\nDone! Inserted ${count} recipes.`);
  process.exit(0);
}

main().catch((err) => {
  console.error('Error:', err);
  process.exit(1);
});
